# Dataset

In [ ]:
from datasets import load_dataset


ds = load_dataset("mohamedemam/Arabic-samsum-dialogsum")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001-8a0858979d62de(…):   0%|          | 0.00/14.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/24813 [00:00<?, ? examples/s]

In [ ]:
ds

DatasetDict({
    train: Dataset({
        features: ['index', 'id', 'dialogue', 'summary', 'topic'],
        num_rows: 24813
    })
})

In [ ]:
ds.data

{'train': MemoryMappedTable
 index: int64
 id: string
 dialogue: string
 summary: string
 topic: string
 ----
 index: [[0,1,2,4,5,...,1215,1216,1217,1218,1220],[1221,1222,1223,1224,1225,...,2423,2424,2425,2426,2429],...,[27796,27797,27798,27799,27800,...,29014,29015,29016,29017,29018],[29019,29020,29021,29022,29023,...,29993,29994,29996,29998,29999]]
 id: [["13821719","13680641","train_4913","13813262","train_6610",...,"13682096","13809869","train_2505","13814969","train_838"],["train_7753","13612216","train_11340","train_91","13611386",...,"13810127","13865429","train_6448","13728577","13816754"],...,["train_3218","13730077","train_2780","13717250","train_12050",...,"train_12019","13680273","test_285_2","train_5991","13820421"],["13829197","train_10175","13828683","13682218","13864584",...,"13729868","train_5270","13681943","13829198","13810241"]]
 dialogue: [["أوبرا: خمن ما أعطانيه جو ليومبي
  نايجل: الجوارب؟
  ميني: هزة الجماع؟
  أوبرا: <file_photo>
  أوبرا: يا رفاق هم الأسوأ
  نايجل: لول
  ميني: كنت على حق نوعا ما
  أوبرا: أردت أن أذهب إلى هناك بشدة
  نايجل: إذن اشترى لك الطعام؟
  أوبرا: إنه ليس مجرد طعام
  أوبرا: هذه هي الحلويات المفضلة لدي من تركيا
  ميني: لا أحصل على حبك للطعام ولكن كل ما يجعلك سعيدًا
  نايجل: ألا تعاني من حساسية من المكسرات؟
  أوبرا: أنا حساسية من الجوز والكاجو ، لذا فلا بأس
  ميني: تبدو لطيفة جدا
  نايجل: حسنًا
  أوبرا: لديها أيضًا بتلات وردية
  نايجل: تبدو لذيذة","إيليا: مهلا ، في طريقي إلى المكتب.هل يمكنك أن ترسل لي هذا جدول الأعمال لهذا اليوم؟
  بريت: بالتأكيد.إنه جاهز فقط
  إيليا: شكرا.هل كيتلين هناك حتى الآن؟
  بريت: لا ، ليس بعد
  إيليا: حسنًا ، فقط أتساءل.لدينا مكالمة جماعية في التاسعة.
  بريت: هل هذا مع مؤسسة الكرم؟
  إيليا: نعم ، إنهم يفكرون في طلب المنح لدينا ، لكنهم أرادوا إجراء مقابلة معنا أولاً
  بريت: حسنًا ، حظًا سعيدًا في ذلك
  إيليا: شكرا.
  بريت: أرسل للتو جدول أعمال.
  إيليا: حسنًا.سأخبرك عندما أحصل عليه.هل يمكنك التحقق مما إذا كان مارتن هناك؟أنا بحاجة إلى رد على بريد إلكتروني أرسلته إليه
  بريت: إنه على الهاتف ، لكنني سأتحدث معه في أقرب وقت
  إيليا: شكرا.ذكّرني: هل حفلة عيد الميلاد غدًا؟
  بريت: تم تأجيله إلى الخميس.أرسلنا سكوت جميعًا تحديثًا.
  إيليا: هذا صحيح.لا أعرف أين كانت عقلي هذا الأسبوع
  بريت: أعتقد أنني أسمع مارتن يختتم دعوته الآن.
  إيليا: حسنًا ، عظيم.
  بريت: تحدثت معه للتو.إنه يرسل لك البريد الإلكتروني الآن
  إيليا: شكرا رجل.فقط حصلت على جدول الأعمال أيضا.سأراك قليلا.
  بريت: أراك قليلا","الشخص 1: ما رأيك في شركتنا؟
   الشخص 2: أنت الشركة الرائدة في صناعة الكمبيوتر.
   الشخص 1: لماذا تعتقد ذلك؟
   الشخص 2: أولاً ، حصتك الساحقة في السوق العالمية.ثانياً ، تفوقك في المبيعات والأرباح بالإضافة إلى مقدار رأس المال وعدد الموظفين.ثالثًا ، التنوع في خط الإنتاج الخاص بك لا يعلى عليه.
   الشخص 1: في أي عمل تهتم به في هذه المنظمة؟
   الشخص 2: على وجه الخصوص ، أنا مهتم بالتسويق في المجال المحلي.","كلوي: ص.
  باتريشيا: ...
  كلوي: مم ، طيب ، ليلة صعبة: د
  باتريشيا: ما زلت في السرير
  باتريشيا: لكني بحاجة حقًا إلى الماء
  باتريشيا: وهي بعيدة جدًا
  كلوي: على الأقل أنت في مزاج جيد ؛)
  باتريشيا: جيد كما يحصل
  كلوي: هل حصلت على رقم هذا الرجل؟
  باتريشيا: نعم ، فعلت.
  كلوي: و ...؟
  كلوي: هل أعطيته لك؟
  باتريشيا: أنت مجنون؟أنا لا أعطي رقمي للرجال العشوائيين
  كلوي: حتى اللطيف؟؛)
  باتريشيا: هاهاها ، قد لا تكون لطيفة للغاية عندما تكون رصينًا
  كلوي: هيا ، لم أكن في حالة سكر حتى تتمكن من الاعتماد على تقديري ؛)
  كلوي: هل ستتصل به رغم ذلك؟
  باتريشيا: لا أعرف بعد ، بالتأكيد ليس الآن
  كلوي: حسنًا ، بالطبع ليس الآن ، ولكن بشكل عام
  باتريشيا: ربما لا","الشخص 1: ماذا تفعل يا أمي؟
   الشخص 2: أحصل على شيء جاهز للغد.غدا هو يوم تروي.
   الشخص 1: يوم زرع الأشجار؟ماذا يفعل الناس في هذا اليوم يا أمي؟
   الشخص 2: كثير من الناس سيذهبون ويزرعون الأشجار.
   الشخص 1: لماذا يفعلون ذلك؟
   الشخص 2: لجعل الأرض أكثر جمالا.وجعل حياتنا أفضل.
   الشخص 1: لكنني غالبًا ما أرى أشخاصًا على شاشة التلفزيون يقطعون العديد من الأشجار الكبيرة.لماذا يفعلون ذلك يا أمي؟
   الشخص 2: hm ، لصنع الورق والمنازل وجعل حياتنا أفضل.
   الشخص 1: لجعل حياتنا أفضل أيضًا؟أنا فقط لا أفهم.أمي ، لماذا يذهب الكثير من الناس وزراعة الأشجار في نفس اليوم؟
   الشخص 2: أوه ، ابني العزيز.من الصعب أن تشرح لك.عندما تكبر ، سوف تفهم.فقط تذكر أن الأشجار مهمة جدا بالنسبة لنا.",...,"أرنولد: مرحبا مايكل!آسف للكتابة هنا ، لكنني أردت التحدث قريبًا عن شيء ما.
  مايكل: لا مشكلة ، ما هذا؟
  أرنولد: تحدثت إلى توم الليلة الماضية.
  مايكل: حول "منزلنا"؟
  أرنولد: بالضبط ، من الصعب بعض الشيء التحدث معك حول هذا الموضوع.
  مايكل: أعلم أنني لم أكن أفضل رفيق مسطح مؤخرًا ، أنا آسف جدًا.
  أرنولد: أنا سعيد لأنك تفهم ذلك.
  مايكل: إذن ماذا تريد أن تخبرني؟
  أرنولد: نعتقد أنه يجب عليك أن تأخذ المزيد من العناية بالشقة.
  مايكل: أنا أعلم ، كنت أتوقع ذلك.أنا آسف ، لقد قضيت وقتًا عصيبًا مؤخرًا
  أرنولد: لا مشكلة ، يمكنك دائمًا أن تقول أن هناك بعض المشكلات حتى لا تفعل شيئًا ، لكننا لا نحب أنك تتجاهل التزاماتك وجهودنا.
  مايكل: سوف يتغير ، أعدك.
  أرنولد: حسنًا ، لا مشكلة :) لنتحدث عندما نكون جميعًا في المنزل.
  مايكل: الليلة؟
  أرنولد: نعم
  مايكل: طيب!","أمي: تذكر أن تأخذ مظلة ، إنها تمطر في الخارج
  سارة: حسنًا ، أمي
  أمي: يوم جيد يا حلوتي
  سارة: شكرا ، أنت أيضًا يا أمي","الشخص 1: هل تعرف أي شخص خضع لعملية جراحية تجميلية؟
   الشخص 2: تقصد مثل تكبير الثدي؟لا أعتقد أن هذا ضروري حقًا.هذه ليست الطريقة التي يجب أن تظل بها المرأة جذابة.
   الشخص 1: لماذا لا؟لماذا لا يمكننا العودة إلى الطريقة التي كانت بها الأمور؟
   الشخص 2: لأن...لا أعرف.لكن ، كوني ، لن تفعل ذلك ، أليس كذلك؟
   الشخص 1: رتق حق أود!
   الشخص 2: ربما يكون المكياج كافيًا؟
   الشخص 1: هيا ، ليز.كن متفتح الذهن!انظر إلى عيني ، فهي منتفخة.وأكياس عيني ، فهي مظلمة وفضفاضة ومليئة بالخطوط والدوائر.آمل حقًا أن تتمكن الجراحة من مسح المشاعر المتعبة.
   الشخص 2: ولكن ماذا يعتقد الآخرون؟
   الشخص 1: لا يهمني ما يعتقده الآخرون.أنا مستعد للرفع.","تايلور: أين وصلت؟
  أوين: لقد عبرت للتو لوس أنجلوس
  تايلور: سوف ينتظر :)","الشخص 1: أريد تسجيل الوصول الآن.ها هي تذكرتي.
   الشخص 2: أليس لديك أي أمتعة لتسجيل الوصول؟
   الشخص 1: لا ، سيدي.
   الشخص 2: هل لديك تفضيل المقعد؟
   الشخص 1: أود مقعد الممر.أشعر بالرعب بالقرب من النافذة.
   الشخص 2: هنا تمريرة الصعود إلى الطائرة.طاب يومك."],["الشخص 1: هل تخبرني كيف يجب أن أرسل هذا الطرد إلى شنغهاي ، الصين؟أنه يحتوي على كتب فقط.
   الشخص 2: قد ترسلها مسألة.
   الشخص 1: أتساءل عما إذا كان بإمكاني تأمينها هنا؟
   الشخص 2: بالطبع.كم تريد تأمين هذه الكتب؟
   الشخص 1: دعني أرى...أعتقد أنه يمكنني الحصول على مؤمن عليهم مقابل خمسمائة دولار.
   الشخص 2: خمسمائة دولار ، لذلك تدفع عشرة دولارات للتأمين ، وهذا هو 2 في المئة من القيمة الإجمالية للمقال.
   الشخص 1: هنا شيك بنسبة عشرة دولارات.","كيم: يا بن ، أرى أنك متصل بالإنترنت اليوم.
  بن: مهلا
  كيم: أنت بشكل جيد في هذه الأيام هل تعلم ذلك؟
  بن: لا شيء مجرد تعطل.
  كيم: ما الذي حصلت عليه في رسالتك؟
  بن: أعتقد أن مكان الإنترنت هو البحث عن المبرمجين ، هل أقرأ هذا بشكل صحيح ؟؟
  كيم: دعني أرى ، .. أنت على حق.
  بن: umhh ..
  كيم: ماذا تفعل الليلة بن ، بيتزا مع فحم الكوك؟مثلما فعلنا ذلك آخر مرة؟
  بن: لا لا ، لقد حصلنا على ذلك مرة أخرى بالتأكيد ، هل تمانع إذا تلقيت فحص المطر؟
  كيم: بالتأكيد ، هل سأراك الليلة.
  بن: سأتصل بك.
  كيم: سأنتظر ..","الشخص 1: مرحبًا.
   الشخص 2: مرحبا ، جون.مرحبًا ، لقد قمت بعمل جيد في تزيين هذا المكان ، لطيف حقًا.
   الشخص 1: شكرا ، أنا سعيد لأنك أعجبك.هل يمكنني الحصول على مشروب؟
   الشخص 2: لا ، شكرا.دعونا نكون العشاء.أنا أشعر بالجوع.
   الشخص 1: ها هو المطبخ.سأغسل البصل أولاً.هل يمكنك إخراج اللحم من الثلاجة؟إنه في حاوية بلاستيكية صفراء.
   الشخص 2: واو ، هذه رائحة جيدة.
   الشخص 1: هل يمكن أن تمرر هذه البطاطس إلي ، من فضلك؟
   الشخص 2: ماذا نواجه؟
   الشخص 1: الزلابية الخاصة الخاصة بي ولحم الخنزير الحلو والحامض ولحم البقر مع البصل والفلفل الأخضر ، وبعض الأطباق الجانبية مثل الطماطم مع السكر.
   الشخص 2: يبدو رائعا.ماذا ستفعل بعد ذلك؟
   الشخص 1: سأبدأ في إعداد حشو اللحوم.
   الشخص 2: الزلابية رائعة.أتمنى لو كان لدي الوصفة.وهل يمكن أن تخبرني ماذا يوجد في هذا؟
   الشخص 1: حسنًا ، لقد وضعت الكثير من البصل فيه ، والثوم والبطيخ.
   الشخص 2: أوه ، أحب الثوم والبطيخ.","الشخص 1: مرحبا بوب.هذا هو نانسي التحدث.أنا سعيد جدًا لأنني أمسك بك أخيرًا.
   الشخص 2: هل كنت تحاول التواصل معي؟إذا لم أكن في المنزل ، فيمكنك عادة الوصول إلي في ناديي هنا.
   الشخص 1: من الجيد معرفة ذلك.اسمع ، بوب ، لدي أخبار لك.
   الشخص 2: ما هذا؟
   الشخص 1: أختي آمي تعود من الولايات.
   الشخص 2: هذا رائع.متى ستعود؟
   الشخص 1: عطلة نهاية الأسبوع القادمة.
   الشخص 2: عطلة نهاية الأسبوع القادمة؟نعم.دعنا نجتمع الليلة ونخطط لحفلة لها.
   الشخص 1: حسنًا.","ديريك: يا كريس ، إنه ديريك من أمس.ستعمل حفنة منا على لعب الهوكي يوم السبت وذكرت أنك ترغب في اللعب ، لذا إذا أردت ، فلا تتردد في الانضمام
  كريس: يا رجل ، شكرا للوصول.لا أستطيع أن أفعل هذا السبت ، هل هناك أي فرصة لقاء يا رفاق في أي يوم آخر؟
  ديريك: حسنًا ، عادةً ما أذهب يوم السبت ولكن إذا ذهبت إلى النادي ، فأنا متأكد من أنه سيكون هناك شخص ما هناك.يحب رفاقي التسكع هناك ، لقد حصلوا على طعام لائق والبيرة رخيصة!
  كريس: حسنًا ، هتاف ، أنا مجاني في نهاية الأسبوع المقبل ، يا رفاق ستكون هناك؟
  ديريك: بالتأكيد.عادة ، وصلنا إلى عدة مباريات في am ثم التسكع فقط
  كريس: بارد.أي شيء أحتاج إلى إحضاره؟
  ديريك: فقط معداتك المعتادة.إذا نسيت أي شيء ، فهناك دائمًا شخص لديه إضافات
  كريس: بارد بارد ، سأبذل في المرة القادمة في ذلك الوقت.شكرا يا صديقي ، من الرائع دائمًا تلبية بعض شركتك الجديد
  ديريك: لا تقلق.احصل على جولة من البيرة وسوف تتناسب بشكل صحيح
  كريس: سيفعل :) أراك بعد ذلك!",...,"سيلفيا: مرحبًا يا عزيزتي هيلين ، يجب أن أعتذر عن عدم الاتصال بك في وقت سابق.إنها فوضى من حولي ، بالكاد أستطيع التفكير!moving house ، marian's lab و تلك الأشياء ...
  هيلين: مرحبًا سيلفيا ، اعتقدت أنك قد تكون مشغولاً للغاية لتجنيبنا بعض الوقت.لا شكر على واجب!كيف هي الأشياء؟
  سيلفيا: الفوضى حقا!ماريان تقضي طوال اليوم في الكلية أيضًا.لذلك تركت وحدي مع كل الاستعدادات.كل هذا العمل!
  هيلين: فقير لك!متى تنتقل إلى المنزل إذن؟
  سيلفيا: ربما في منتصف يوليو.يعتمد على العمال هناك.وعلى ماريان!
  هيلين: تقصد أن المنزل لم ينته؟!
  سيلفيا: يقولون إنه كان لدي نظرة فاحصة على الصور التي أرسلوها وكانوا مرعوبين.كان لدى ماريان "مؤتمر فيديو" معهم وأرسلهم العمل مرة أخرى.
  هيلين: إنه أمر صعب عندما لا تراقبهم.أنت تعرف ، الإشراف.
  سيلفيا: هذه هي النقطة!يجب أن تكون ماريان هناك قبل أسابيع ، لكنه يقول إن مختبره أكثر أهمية الآن من منزلنا.أشعر بائسة جدا!
  هيلين: أوه لا!حتى لو لم يكن المنزل مثاليًا في التحرك ، فيمكنك دائمًا إجراء تحسينات لاحقًا.
  سيلفيا: هذا ما تقوله ماريان.وأنا أعلم أنه معقول.أنا أعرف...
  هيلين: لذا توقف عن القلق!
  سيلفيا: نعم ... علي فقط أن أهدأ قليلاً.استرخ لبضع ساعات.
  هيلين: لماذا لا نذهب إلى هذا المنتجع الصحي بالقرب من dartport؟فقط بعد ظهر يوم واحد؟
  سيلفيا: يا سيلفيا!أنت تعرف؟دعني افكر به.
  هيلين: فقط أخبرني متى وسأرتب الباقي.
  سيلفيا: أنت ملاك!","تيريزا: إلى أين أنت ذاهب الليلة؟
  ماري: لأننا لم نقرر للغاية
  ماري: شاطئ؟
  جيف: لا ، يبدو أن لدينا ما يكفي
  جيف: حديقة مورن تروا بيتونز الوطنية لرؤية بحيرة الغليان
  تيريزا: يبدو جيدا!هل يمكننا الانضمام؟
  مايلز: بالتأكيد ، إنها ثاني أكبر بحيرة ساخنة في العالم
  ماري: أنت مجرد رفاق رائعين ، أفكار رائعة دائمًا!","الشخص 1: معذرة ، أود إرسال هذا الطرد.
   الشخص 2: ماذا يوجد في ذلك ، من فضلك؟
   الشخص 1: فقط عدد قليل من القمصان.
   الشخص 2: حسنًا.يمكنك لفه الآن.يرجى ملء هذا النموذج وتسميته.(بعد لحظة) هل ترغب في تسجيلها؟
   الشخص 1: لا ، أفضل إرساله بالبريد العادي.
   الشخص 2: تسعة دولارات وخمسين سنتًا.
   الشخص 1: أنت هنا.
   الشخص 2: ها هو الإيصال.
   الشخص 1: شكرا جزيلا لك.
   الشخص 2: على الرحب والسعة.","لوسي: لا أعرف أين هو هاتفي هل يمكنك الاتصال بي؟
  سام: الاتصال
  لوسي: حصلت عليه ، شكرا!","كينزي: لقد كنت أبحث عن متجر جيد للآيس كريم للذهاب مع عائلتي
  فرانك: حظا سعيدا
  كينزي: أين كانت أفضل تجربة الآيس كريم؟:/
  فرانك: أنا دائمًا أذهب إلى بابا جينو
  كينزي: شكرا على الاقتراح
  فرانك: np
  كينزي: تريد أن تأتي؟
  فرانك: ناه ، أنا جيد"],...,["الشخص 1: مساء الخير يا سيدتي.هل لديك حجز؟
   الشخص 2: لا ، أنا لا.
   الشخص 1: آسف للغاية ، ولكن لا توجد طاولات فارغة الآن.
   الشخص 2: حسنًا ، هل يمكن أن تخبرني كم من الوقت في الانتظار تعتقد أنه سيكون هناك؟
   الشخص 1: حوالي 15 دقيقة على ما أعتقد.هل هذا جيد بالنسبة لك؟
   شخص 2: 15 دقيقة؟هذا سيء للغاية.لا استطيع الانتظار لفترة طويلة.
   الشخص 1: أنا آسف يا سيدتي.
   الشخص 2: هل أنت متأكد من أنه لا توجد طاولات فارغة على الإطلاق؟هل يمكنك من فضلك فقط تحقق لي؟
   الشخص 1: حسنًا ، سوف أتحقق مرة أخرى من أجلك.
   الشخص 2: حسنًا ، سأنتظر لحظة.
   الشخص 1: أنا آسف جدًا لخطري.هناك جدول متاح في قسم التدخين.
   الشخص 2: جيد.
   الشخص 1: لكنه في قسم التدخين.هل تمانع يا سيدتي؟
   الشخص 2: أعتقد أنه ليس لدي خيار الآن.
   الشخص 1: من فضلك اتبعني بعد ذلك.سأريك على طاولتك.
   الشخص 2: شكرا.
   الشخص 1: على الرحب والسعة.سيكون الخادم معك على الفور لاتخاذ طلبك.آسف مرة أخرى على إهمال بلدي.
   الشخص 2: لا تذكره.","جيمس: أنا أقود السيارة هناك ، هل أحتاج إلى رحلة؟
  ريتشارد: هذا مثالي ، شكرًا ، في أي وقت يجب أن أكون جاهزًا؟
  جيمس: 6:15؟
  ريتشارد: سأنتظر!","الشخص 1: هل فكرت في ما ستفعله بعد الانتهاء من المدرسة؟
   الشخص 2: هم ... من أين تبدأ؟
   الشخص 1: حسنًا.أعتقد أن أفضل طريقة هي البدء في التفكير في الوظائف التي قد تجدها مثيرة للاهتمام.بالنسبة لي ، أحب وظائف الإثارة.لذلك أريد أن أكون سائق سباق.
   الشخص 2: هذا رائع ، لكنني أعتقد أنه أمر خطير.
   الشخص 1: إنه أيضًا وظيفة والدي وسأسأله عن ذلك.الآن ماذا عنك؟
   الشخص 2: حسنًا ... أحب أن أكون في الهواء الطلق.كما أود أن أساعد الناس بطريقة ما.
   الشخص 1: حسنًا.غالبًا ما يعمل رجال الإطفاء في الهواء الطلق ويساعدون الآخرين.لكن مثل هذه الوظيفة مناسبة للنساء.
   الشخص 2: نعم ، أه ، كانت وظيفة المرشد السياحي جذابًا بالنسبة لي.
   الشخص 1: هذا يبدو وكأنه وظيفة مناسبة لك.","جوناثان: yoo guys darren: b-) lucas: hey wassup jonathan: beer؟الآن؟دارين: الجحيم نعم ب) لوكاس: أنا حر في المساء","الشخص 1: يسمى هذا القسم من المتجر جونيور.لماذا هذا؟
   الشخص 2: هذا يعني الفتيات الصغيرات.هذا هو المكان الذي ستجد فيه ملابس للفتيات الصغيرات.
   الشخص 1: لكن لا يمكنني العثور على أي شيء في مقاسي هنا.
   الشخص 2: أنت صغير ، لكنك لست طفلاً.
   الشخص 1: حسنًا ، لا يوجد شيء يمكنني فعله حيال طولي!
   الشخص 2: هناك قسم صغير يمكنك التحقق منه.
   الشخص 1: ماذا يوجد في القسم الصغير؟
   الشخص 2: لديه ملابس بأحجام صغيرة للنساء الصغيرات.",...,"الشخص 1: دونا ، لقد صدمت الجميع حقًا في الحفلة الليلة الماضية!
   الشخص 2: تقصد بأدائي؟
   الشخص 1: نعم!لقد افترضنا جميعًا أنك من النوع الهادئ الخجول.
   الشخص 2: أعتقد أن كل شخص لديه بعض الأسرار.
   الشخص 1: أين تعلمت أن تغني هكذا؟
   الشخص 2: كنت جزءًا من فرقة في المدرسة.
   الشخص 1: أنت؟رائع.ولماذا لا ترتدي مثل هذا في العمل؟
   الشخص 2: هيا!هذا هو العمل.ألا تعتقد أن هذا سيكون غريبًا بعض الشيء؟","داني: ماذا لديك؟
  نويل: مم لدي واحدة من أفضل وجبة ممكنة الآن :) سمك السلمون مع الخضار
  داني: جيد لك ؛) أنا أحب سمك السلمون","الشخص 1: غدا هو عيد ميلاد مايك.لقد تلقيت للتو الدعوة إلى حزبه.هل دعوك مايك أيضًا؟
   الشخص 2: نعم.تلقيت دعوته هذا الصباح.لكنه لم يخبرني في الوقت الذي سيبدأ فيه الحزب.
   الشخص 1: سأرنه وأسأله عن ذلك.كيف ستذهب إلى حزبه؟
   الشخص 2: سأذهب إلى حزبه بعد العمل.هل ترغب في أخذ سيارتي هناك؟
   الشخص 1: سأكون سعيدًا.شكرًا لك.","الشخص 1: أنا أتحدث مع جاكي جولد ، وهي أم فخورة جدًا.ظهرت ابنتها أوليفيا ، على مسرح مسرح بلندن بالاديوم في the musical ، the sound of music الشهر الماضي.فكيف حدث كل شيء؟
   الشخص 2: حسنًا ، حتى العام الماضي ، كانت فكرة ظهورها في البلاديوم في لندن لا يمكن تصورها لعائلتنا.بدأت الأمور تحدث عندما حصلت أوليفيا على الدور الرائد لعرض آني في المسرح المحلي.بالنسبة لآني ، كان على أوليفيا معرفة أكثر من 200 سطر.كانت على خشبة المسرح من معظم عرض ساعتين.قررت أن نفعل 10 صفحات في الليلة.بعد حفظها ، أعطيتها خطًا وسيتعين عليها أن تخبرني ما هو السطر التالي.لقد التقطت كل شيء أفضل من واجباتها المنزلية.
   الشخص 1: وقد فعلت ذلك بشكل جيد في الجزء.
   الشخص 2: كانت رائعة في الجزء.كانت دائمًا خجولة وأصبحت فجأة أقل خجولة وأكثر ثقة.كان أحد أعضاء فريق إدارة المسرح للمعرض سيطر على وكالة محلية وطلب منها الاشتراك.إذن كان لديها وكيل لتمثيلها ومحاولة الحصول على أدوار لها.","دوروثي: أبحث عن حاضنة طفل.
  دوروثي: هل يمكنك أن توصي بشخص ما؟
  أماندا: لديّ موصىف
  أماندا: كان لدي تجربة سيئة لن أترك طفلي مع شخص ما مرة أخرى
  غريتا: ماذا حدث؟😱
  غريتا: يمكنني أن أوصي بعمي.
  غريتا: إنها تساعدني مع مايك
  غريتا: لكن ليس لدي أي فكرة عن مدى شحنها
  غريتا: إنها طالبة ربما ليس كثيرًا
  دوروثي: أماندا ولكن ماذا حدث ؟؟
  أماندا: بمجرد أن عدت إلى المنزل في وقت مبكر وكانت سخيف مع رجل على أريكتي.كان توم بلدي على الأرض يبكي.
  دوروثي: هذا فظيع!☹
  دوروثي: من كانت ؟؟
  أماندا: شخص ما أوصت ... 😡"],["جورج: مرحبا هناك!
  تيم: غوتن أبيند ، هير فيشر!
  جورج: غوتن أبيند.إذن أنت قادم إلى فرانكفورت غدًا ، أليس كذلك؟
  تيم: نعم ، جيمي ، هال وأنا.أراك غدا!
  جورج: عظيم!استمتع برحلتك","الشخص 1: هل تعرف أين يمكنني العثور على صناديق الموسيقى القديمة؟
   الشخص 2: يمكنك محاولة التسوق في سوق السلع المستعملة.
   الشخص 1: ما هذا؟لم أسمع أبدا من شيء من هذا القبيل.
   الشخص 2: سوق السلع المستعملة هو مكان في الهواء الطلق حيث يبيع الناس جميع أنواع الأشياء المستخدمة.
   الشخص 1: حسنًا ، أين يمكنني أن أجد واحدة؟
   الشخص 2: حسنًا ، يمكنك التحقق من الورقة المحلية أو البحث عن "سوق السلع المستعملة" عبر الإنترنت.","كلاي: انظر ، أنا حقا آسف ، لقد تصرفت بشكل رهيب ... لقد أرسلت لك المال.أعدك أنه لن يحدث مرة أخرى :)
  ريتا: ليس عليك أن تعد بأي شيء - لقد كان رد فعل بشري طبيعي (ولكنه غبي إلى حد ما): p
  كلاي: أشعر بالسوء لأنني كذبت عليك ...لقد رفضوا الاقتراح مع الاتحاد الأوروبي ... أظن أنه إما بريطانيا من الاتحاد الأوروبي أو أنا دونو ، إنهم يحاولون التخلص من تيريزا ماي
  ريتا: حسنًا ، هذا لا شيء جديد","ويلي: البيرة الليلة؟
  تريشيا: بالتأكيد
  ويلي: أراك بعد ذلك","تيريزا: سأذهب إلى موعد يوم السبت.
  بلانكا: يا إلهي مع من ؟؟
  قزحية: لقد مر بعض الوقت ...
  تيريزا: أعرف
  تيريزا: إنه رجل جيد المظهر
  تيريزا: قابلته في النادي
  بلانكا: الشخص الذي تحدثت إليه؟
  تيريزا: نعم :-)
  إيريس: هل أخبرك أنه جاء من السماء؟
  بلانكا: وأنك أجمل من جميع الملائكة التي رآها هناك؟
  تيريزا: كيف تعرف؟
  بلانكا: هذا الرجل لديه سمعة ...
  قزحية: وأيضًا ديك كبير
  قزحية: استمتع بها بينما تستمر
  تيريزا: هل نمت معه؟
  بلانكا: فعل جميع الفتيات في النادي
  هناك: :-(",...,"باميلا: يا إلهي ، لقد رأيت للتو روبن هود!
  سكوت: هل أعجبك؟
  باميلا: نعم ، أحببت ذلك ، وخاصة تارون إيغرتون
  سكوت: شعرت بالملل قليلاً ، إنها نفس القصة التي روىها مرارًا وتكرارًا
  باميلا: حسنًا ، أنت على حق ، لكن بالنسبة لي كانت لا تزال مسلية
  سكوت: رغم أن جيمي فوكس كان بعيدًا عن دوره
  باميلا: لم يعجبني أبدًا أنني لم أهتم به كثيرًا xd
  سكوت: كان بعض الشيء عنيفًا ودمويًا بالنسبة لي
  باميلا: سكوتي ، هذا ما يشبه فيلم الإجراءات: د
   سكوت: الكل في الكل ، لم يكن فيلمًا بالنسبة لي :)
  باميلا: سكوتي ، كنت دائمًا مختلفًا ؛-)","الشخص 1: ماذا ستفعل إذا فزت بمبلغ 1،000،000 دولار؟
   الشخص 2: أوه ، لا أعرف.أعتقد أنني سأشتري سيارة.
   الشخص 1: هذا لا يبدو ممتعًا للغاية.
   الشخص 2: حسنًا ، ماذا ستفعل؟
   الشخص 1: سأذهب في رحلة حول العالم.
   الشخص 2: إلى أين تذهب؟
   الشخص 1: أول مكان أذهب إليه هو باريس.لطالما أردت الذهاب للتسوق في باريس.
   الشخص 2: هذه فكرة جيدة.يمكنك إنفاق بعض أموالك هناك.
   الشخص 1: نعم ، ثم أعتقد أنني سأذهب إلى روما.أنا أحب الطعام الإيطالي بشكل أفضل.
   الشخص 2: أنا أيضًا.
   الشخص 1: بعد ذلك سأذهب إلى مصر لرؤية الأهرامات ، ثم إلى أستراليا لرؤية الحاجز المرجاني العظيم.لكن بعد ذلك ، لست متأكدًا من أين أذهب.أين تود الذهاب؟
   الشخص 2: إذا كنت في رحلة كهذه ، فسأذهب إلى ألمانيا لمعرفة أين يصنعون bmws.
   الشخص 1: بالطبع ، تحب تلك السيارات.
   الشخص 2: نعم ، هذا صحيح.لكني أود أيضًا مشاهدة مباراة كرة قدم.الفريق الألماني هو المفضل لدي.","فيليس: قطتي مدهشة
  فيليس: أيقظني في الساعة 3 صباحًا
  فيليس: بدأ في الترويج وأراد أن يكون حيوانًا أليفًا
  فيليس: أنا أليفه عدة مرات ولكني كنت متعبًا
  فيليس: لذلك توقفت وأغفو مرة أخرى
  فيليس: لذلك فتح خزانة ملابسي وبدأ في سحب جميع البلوزات:@
  كريج: <lol>","ستيف: أنا سعيد لأنك أحببت القصة.
  أندي: صدق أو لا تصدق ولكني قرأته في نهاية الأسبوع الماضي.
  أندي: ما زلت بحاجة إلى قراءتها مرة أخرى لتكون قادرًا على إخبار شيء بناءً عليه.
  ستيف: مجرد اختبار الخرف الخاص بك: p
  أندي: قد أكون قديمًا ولكن ليس هذا قديمًا: p
  أندي: يستغرق الأمر وقتًا طويلاً لكتابة شيء بناء خاصة بعد المرور مرة واحدة فقط.
  ستيف: أنا أقدر ذلك.
  ستيف: كانت تلك القصة تحويلًا لأحد أنثر الذي كان لدي في رأسي لمدة 10 سنوات.
  أندي: هل كتبت في الأصل باللغة السويدية؟
  ستيف: نعم.
  ستيف: لكن الفكرة الأصلية كانت تدور حول الذكاء الاصطناعي الذي كان يبني جسمًا لنفسه ، android ثم الإنسان.
  أندي: حسنًا ، يمكنني أن أقول أنه تم ترجمته ، ولم أحصل على ذلك من أول أول واحد أرسلته.
  ستيف: أوه لا.
  ستيف: هذا يعني أنه لا يزال هناك عمل يتعين القيام به.
  ستيف: لقد أصلحت بعض الأشياء الغريبة ولكن يبدو أنها لم تكن كافية.

In [ ]:
ds.column_names

{'train': ['index', 'id', 'dialogue', 'summary', 'topic']}

In [ ]:
ds["train"]

Dataset({
    features: ['index', 'id', 'dialogue', 'summary', 'topic'],
    num_rows: 24813
})

In [ ]:
ds["train"]["index"]

Column([0, 1, 2, 4, 5])

In [ ]:
ds["train"]["summary"][50]

'ليفاندوفسكا لديه الحصبة.هناك لقاحات في المبنى الرئيسي من 17 حتى التاسع عشر لكل من كان على اتصال معها.'

In [ ]:
ds["train"]["dialogue"][50]

'جوانا: يرسلون رسائل بريد إلكتروني حول ليفاندوفسكا.\n ميرف: ماذا حدث؟\n جوانا: <file_photo>\n ميرف: ووو!\n جوانا: تم نقلها إلى المستشفى لأنها تعاني من الحصبة.\n ميرف: كان لديها ماذا؟\n جوانا: يجب على أي شخص لديه اتصال معها خلال اليومين الماضيين تلقيح.\n ميرف: لحسن الحظ لم أرها منذ الفصل الدراسي الأخير ...\n جوانا: فعلت ، هي معلمتي أطروحة :(\n ميرف: ماذا ستفعل؟\n جوانا: إنهم ينظمون اللقاحات في المبنى الرئيسي من 17 حتى التاسع عشر.\n ميرف: عليك أن تذهب!\n جوانا: أعرف ... وبدأت للتو العمل ، لذا ليس لدي الكثير من الوقت.\n ميرف: هيا ، هذا مهم حقا.\n جوانا: سأحاول القيام بذلك قبل العمل في الثامنة عشرة ، وآمل ألا أفقد اليوم بأكمله ...'

In [ ]:
ds["train"]["dialogue"][50].split(':')

['جوانا',
 ' يرسلون رسائل بريد إلكتروني حول ليفاندوفسكا.\n ميرف',
 ' ماذا حدث؟\n جوانا',
 ' <file_photo>\n ميرف',
 ' ووو!\n جوانا',
 ' تم نقلها إلى المستشفى لأنها تعاني من الحصبة.\n ميرف',
 ' كان لديها ماذا؟\n جوانا',
 ' يجب على أي شخص لديه اتصال معها خلال اليومين الماضيين تلقيح.\n ميرف',
 ' لحسن الحظ لم أرها منذ الفصل الدراسي الأخير ...\n جوانا',
 ' فعلت ، هي معلمتي أطروحة ',
 '(\n ميرف',
 ' ماذا ستفعل؟\n جوانا',
 ' إنهم ينظمون اللقاحات في المبنى الرئيسي من 17 حتى التاسع عشر.\n ميرف',
 ' عليك أن تذهب!\n جوانا',
 ' أعرف ... وبدأت للتو العمل ، لذا ليس لدي الكثير من الوقت.\n ميرف',
 ' هيا ، هذا مهم حقا.\n جوانا',
 ' سأحاول القيام بذلك قبل العمل في الثامنة عشرة ، وآمل ألا أفقد اليوم بأكمله ...']

In [ ]:
ds["train"]["dialogue"][50].split()

['جوانا:',
 'يرسلون',
 'رسائل',
 'بريد',
 'إلكتروني',
 'حول',
 'ليفاندوفسكا.',
 'ميرف:',
 'ماذا',
 'حدث؟',
 'جوانا:',
 '<file_photo>',
 'ميرف:',
 'ووو!',
 'جوانا:',
 'تم',
 'نقلها',
 'إلى',
 'المستشفى',
 'لأنها',
 'تعاني',
 'من',
 'الحصبة.',
 'ميرف:',
 'كان',
 'لديها',
 'ماذا؟',
 'جوانا:',
 'يجب',
 'على',
 'أي',
 'شخص',
 'لديه',
 'اتصال',
 'معها',
 'خلال',
 'اليومين',
 'الماضيين',
 'تلقيح.',
 'ميرف:',
 'لحسن',
 'الحظ',
 'لم',
 'أرها',
 'منذ',
 'الفصل',
 'الدراسي',
 'الأخير',
 '...',
 'جوانا:',
 'فعلت',
 '،',
 'هي',
 'معلمتي',
 'أطروحة',
 ':(',
 'ميرف:',
 'ماذا',
 'ستفعل؟',
 'جوانا:',
 'إنهم',
 'ينظمون',
 'اللقاحات',
 'في',
 'المبنى',
 'الرئيسي',
 'من',
 '17',
 'حتى',
 'التاسع',
 'عشر.',
 'ميرف:',
 'عليك',
 'أن',
 'تذهب!',
 'جوانا:',
 'أعرف',
 '...',
 'وبدأت',
 'للتو',
 'العمل',
 '،',
 'لذا',
 'ليس',
 'لدي',
 'الكثير',
 'من',
 'الوقت.',
 'ميرف:',
 'هيا',
 '،',
 'هذا',
 'مهم',
 'حقا.',
 'جوانا:',
 'سأحاول',
 'القيام',
 'بذلك',
 'قبل',
 'العمل',
 'في',
 'الثامنة',
 'عشرة',
 '،',
 'وآمل',
 'ألا',
 'أفقد',
 'اليوم',
 'بأكمله',
 '...']

In [ ]:
ds["train"]["dialogue"][50].split('\n')

['جوانا: يرسلون رسائل بريد إلكتروني حول ليفاندوفسكا.',
 ' ميرف: ماذا حدث؟',
 ' جوانا: <file_photo>',
 ' ميرف: ووو!',
 ' جوانا: تم نقلها إلى المستشفى لأنها تعاني من الحصبة.',
 ' ميرف: كان لديها ماذا؟',
 ' جوانا: يجب على أي شخص لديه اتصال معها خلال اليومين الماضيين تلقيح.',
 ' ميرف: لحسن الحظ لم أرها منذ الفصل الدراسي الأخير ...',
 ' جوانا: فعلت ، هي معلمتي أطروحة :(',
 ' ميرف: ماذا ستفعل؟',
 ' جوانا: إنهم ينظمون اللقاحات في المبنى الرئيسي من 17 حتى التاسع عشر.',
 ' ميرف: عليك أن تذهب!',
 ' جوانا: أعرف ... وبدأت للتو العمل ، لذا ليس لدي الكثير من الوقت.',
 ' ميرف: هيا ، هذا مهم حقا.',
 ' جوانا: سأحاول القيام بذلك قبل العمل في الثامنة عشرة ، وآمل ألا أفقد اليوم بأكمله ...']

In [ ]:
ds["train"]["summary"][50].split()

['ليفاندوفسكا',
 'لديه',
 'الحصبة.هناك',
 'لقاحات',
 'في',
 'المبنى',
 'الرئيسي',
 'من',
 '17',
 'حتى',
 'التاسع',
 'عشر',
 'لكل',
 'من',
 'كان',
 'على',
 'اتصال',
 'معها.']

# Preprocessing

####temporary tokenization

#####wont tokenize and will use the modeol tokenizer instead

In [ ]:
from nltk.tokenize import SpaceTokenizer
SpaceTokenizer().tokenize(ds["train"]["summary"][50])

['ليفاندوفسكا',
 'لديه',
 'الحصبة.هناك',
 'لقاحات',
 'في',
 'المبنى',
 'الرئيسي',
 'من',
 '17',
 'حتى',
 'التاسع',
 'عشر',
 'لكل',
 'من',
 'كان',
 'على',
 'اتصال',
 'معها.']

In [ ]:
from nltk.tokenize import PunktSentenceTokenizer
PunktSentenceTokenizer().tokenize(ds["train"]["summary"][50])

['ليفاندوفسكا لديه الحصبة.هناك لقاحات في المبنى الرئيسي من 17 حتى التاسع عشر لكل من كان على اتصال معها.']

In [ ]:
from nltk.tokenize import WordPunctTokenizer
tokenizer = WordPunctTokenizer()
print(tokenizer.tokenize(ds["train"]["dialogue"][50]))

['جوانا', ':', 'يرسلون', 'رسائل', 'بريد', 'إلكتروني', 'حول', 'ليفاندوفسكا', '.', 'ميرف', ':', 'ماذا', 'حدث', '؟', 'جوانا', ':', '<', 'file_photo', '>', 'ميرف', ':', 'ووو', '!', 'جوانا', ':', 'تم', 'نقلها', 'إلى', 'المستشفى', 'لأنها', 'تعاني', 'من', 'الحصبة', '.', 'ميرف', ':', 'كان', 'لديها', 'ماذا', '؟', 'جوانا', ':', 'يجب', 'على', 'أي', 'شخص', 'لديه', 'اتصال', 'معها', 'خلال', 'اليومين', 'الماضيين', 'تلقيح', '.', 'ميرف', ':', 'لحسن', 'الحظ', 'لم', 'أرها', 'منذ', 'الفصل', 'الدراسي', 'الأخير', '...', 'جوانا', ':', 'فعلت', '،', 'هي', 'معلمتي', 'أطروحة', ':(', 'ميرف', ':', 'ماذا', 'ستفعل', '؟', 'جوانا', ':', 'إنهم', 'ينظمون', 'اللقاحات', 'في', 'المبنى', 'الرئيسي', 'من', '17', 'حتى', 'التاسع', 'عشر', '.', 'ميرف', ':', 'عليك', 'أن', 'تذهب', '!', 'جوانا', ':', 'أعرف', '...', 'وبدأت', 'للتو', 'العمل', '،', 'لذا', 'ليس', 'لدي', 'الكثير', 'من', 'الوقت', '.', 'ميرف', ':', 'هيا', '،', 'هذا', 'مهم', 'حقا', '.', 'جوانا', ':', 'سأحاول', 'القيام', 'بذلك', 'قبل', 'العمل', 'في', 'الثامنة', 'عشرة', '،', 'وآمل', 'ألا', 'أفقد', 'اليوم', 'بأكمله', '...']

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\amer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [ ]:
from nltk.tokenize import sent_tokenize
print(sent_tokenize(ds["train"]["dialogue"][50]))

['جوانا: يرسلون رسائل بريد إلكتروني حول ليفاندوفسكا.', 'ميرف: ماذا حدث؟\n جوانا: <file_photo>\n ميرف: ووو!', 'جوانا: تم نقلها إلى المستشفى لأنها تعاني من الحصبة.', 'ميرف: كان لديها ماذا؟\n جوانا: يجب على أي شخص لديه اتصال معها خلال اليومين الماضيين تلقيح.', 'ميرف: لحسن الحظ لم أرها منذ الفصل الدراسي الأخير ...\n جوانا: فعلت ، هي معلمتي أطروحة :(\n ميرف: ماذا ستفعل؟\n جوانا: إنهم ينظمون اللقاحات في المبنى الرئيسي من 17 حتى التاسع عشر.', 'ميرف: عليك أن تذهب!', 'جوانا: أعرف ... وبدأت للتو العمل ، لذا ليس لدي الكثير من الوقت.', 'ميرف: هيا ، هذا مهم حقا.', 'جوانا: سأحاول القيام بذلك قبل العمل في الثامنة عشرة ، وآمل ألا أفقد اليوم بأكمله ...']

##Dataset Cleaning

In [ ]:
#the topics are too varied to be able to make use of them so we will be removing the column
from collections import Counter

# Extract the 'topics' column as a list
topics_list = ds['train']['topic']

# Count unique values
counts = Counter(topics_list)

# Print the counts
print(counts)

Counter({None: 12599, 'shopping': 170, 'job interview': 142, 'daily casual talk': 115, 'order food': 75, 'phone call': 75, 'interview': 62, 'social meeting': 51, 'weather': 45, 'see a doctor': 43, 'invitation': 38, 'daily talk': 34, 'go shopping': 34, 'social casual talk': 31, 'ask for directions': 30, 'business talk': 29, 'ask for information': 29, 'make an appointment': 28, 'ask for help': 28, 'job': 27, 'take a taxi': 27, 'lose weight': 24, 'office talk': 23, 'rent an apartment': 23, 'check in': 22, 'casual talk': 22, 'restaurant service': 22, 'complaint': 22, 'daily conversation': 21, 'weekend plan': 20, 'party': 20, 'Casual talk': 20, 'bank service': 19, 'book a room': 19, 'gossip': 18, 'find a job': 18, 'farewell': 18, 'dinner': 18, 'hotel service': 18, 'dinner invitation': 17, 'appointment': 17, 'party invitation': 17, 'movie': 16, 'borrow money': 16, 'restaurant': 16, 'show the way': 16, 'check out': 16, 'marriage': 16, 'ask the way': 16, 'open an account': 16, 'an interview': 16, 'holiday': 15, 'family': 15, 'future plan': 15, 'social talk': 15, 'sports': 15, 'ask for leave': 15, 'exercise': 15, 'work': 14, 'vacation plan': 14, 'cooking': 14, 'transportation': 14, 'car accident': 14, 'apology': 14, 'vacation': 14, 'schedule': 13, 'birthday gift': 13, 'conversation between friends': 13, 'travel': 13, 'showing the way': 13, 'hobbies': 13, 'break up': 12, 'check-in': 12, 'pay the bill': 12, 'ordering food': 12, 'divorce': 12, 'wedding': 12, 'food ordering': 12, 'birthday': 12, 'ask directions': 12, 'bargain': 12, 'house renting': 12, 'salary': 11, 'holiday plan': 11, 'at the restaurant': 11, 'take a bus': 11, 'travel plan': 11, 'music': 11, 'room service': 11, 'buy clothes': 11, 'school life': 11, 'hobby': 10, 'haircut': 10, 'picnic': 10, 'birthday party': 10, 'school': 10, 'trip': 10, 'smoking': 10, 'rent a car': 10, 'dance': 10, 'leave a message': 10, 'order': 10, 'apartment': 10, 'refund': 10, 'move': 9, 'quarrel': 9, 'buy a car': 9, 'business trip': 9, 'conversation between colleagues': 9, 'watch TV': 9, 'money': 9, 'driving': 9, 'be late': 9, 'have a haircut': 9, 'new job': 9, 'vote': 9, 'argument': 9, 'meeting': 9, 'part-time job': 9, 'test results': 9, 'computer': 9, 'job hunting': 8, 'buy a house': 8, 'online shopping': 8, 'laundry': 8, 'greetings': 8, 'hotel': 8, 'congratulation': 8, 'date': 8, 'lunch': 8, 'library': 8, 'change a room': 8, 'greeting': 8, 'weekend activities': 8, 'illness': 8, 'Christmas': 8, 'a new job': 8, 'find an apartment': 8, 'reading': 8, 'gift': 8, 'room reservation': 8, 'buy a ticket': 8, 'movie invitation': 8, 'introduction': 8, 'promotion': 8, 'business': 8, 'holidays': 8, 'job application': 8, 'breakfast': 8, 'save money': 8, 'language': 8, 'Interview': 8, 'watch a movie': 8, 'an invitation': 8, 'bus pass': 7, 'parking': 7, 'borrow books': 7, 'Shopping': 7, 'Gossip': 7, 'flight': 7, 'presentation': 7, 'help': 7, 'new house': 7, 'a call': 7, 'credit card': 7, 'say goodbye': 7, 'rent a house': 7, 'buy books': 7, 'after-sales service': 7, 'movies': 7, 'accident': 7, 'coffee': 7, 'good news': 7, 'tour plan': 7, 'Chinese food': 7, 'field trip': 6, 'feel sick': 6, 'airport': 6, 'an accident': 6, 'new car': 6, 'diet': 6, 'make a reservation': 6, 'gratitude': 6, 'work overtime': 6, 'movie discussion': 6, 'send a parcel': 6, 'loan': 6, 'stomachache': 6, 'roommate': 6, 'chest X-ray': 6, 'robbery': 6, 'book': 6, 'buy a gift': 6, 'personality': 6, 'party preparation': 6, 'flight delay': 6, 'drink': 6, "Valentine's Day": 6, 'interview preparation': 6, 'concert': 6, 'discuss the weather': 6, 'traffic accident': 6, 'fax machine': 6, 'currency exchange': 6, 'give up smoking': 6, 'camping': 6, 'girlfriend': 6, 'self-introduction': 6, 'visit': 6, 'casual chat': 6, 'company': 6, 'house': 6, 'evening plan': 5, 'asking the way': 5, 'see the doctor': 5, 'restaurant reservation': 5, 'online chatting': 5, 'see a movie': 5, 'concert invitation': 5, 'luggage storage': 5, 'tour': 5, 'tour guide': 5, 'learn English': 5, 'film': 5, 'personal experience': 5, 'weekend': 5, 'mangoes': 5, 'ask questions': 5, 'Birthday': 5, 'spare time activities': 5, 'driving test': 5, 'work out': 5, 'buy a pan': 5, 'take orders': 5, 'study': 5, 'offer help': 5, 'encouragement': 5, 'time': 5, 'traffic jam': 5, 'buying clothes': 5, 'dream': 5, 'hotel reservation': 5, 'withdraw money': 5, 'asking for help': 5, 'play golf': 5, 'vending machine': 5, 'keep fit': 5, 'visa application': 5, 'a new car': 5, 'medicine': 5, 'shopping online': 5, 'rain': 5, 'career': 5, 'investment': 5, 'late for work': 5, 'discuss a person': 5, 'job seeking': 5, 'business negotiation': 5, 'make a call': 5, 'speech': 5, 'quit the job': 5, 'love life': 5, 'dessert': 5, 'summer plan': 5, 'class': 5, 'worry': 5, 'an appointment': 5, 'book a ticket': 5, 'ask for advice': 5, 'call': 5, 'book a table': 5, 'food': 5, 'voting': 5, 'Halloween': 5, 'restaurant talk': 5, 'reservation': 5, 'wash clothes': 4, 'parking permit': 4, 'lateness': 4, 'advertisement': 4, 'buy a coat': 4, 'friend': 4, 'suggestions': 4, 'Saturday plan': 4, 'fishing': 4, 'university': 4, 'rail service': 4, 'take the bus': 4, 'buying a house': 4, 'order some food': 4, 'watch movies': 4, 'being late': 4, 'mail': 4, 'overtime working': 4, 'rent a flat': 4, 'personal information': 4, 'shoes': 4, 'ATM': 4, 'football match': 4, 'quit smoking': 4, 'keep a pet': 4, 'see a house': 4, 'company rules': 4, 'have lunch': 4, 'go sightseeing': 4, 'Movies': 4, 'business card': 4, 'service': 4, 'losing weight': 4, 'cultural difference': 4, 'summer vacation': 4, 'a trip': 4, 'office': 4, 'new apartment': 4, 'love': 4, 'commercial negotiation': 4, 'education background': 4, 'relationship': 4, 'book tickets': 4, 'toothache': 4, 'compliment': 4, 'Restaurant': 4, 'find a book': 4, 'call a taxi': 4, 'pregnancy': 4, 'delayed flight': 4, 'healthy diet': 4, 'plan': 4, 'Australia': 4, 'get married': 4, 'office romance': 4, 'cat': 4, 'see someone off': 4, 'reserve a room': 4, 'at the office': 4, 'dress': 4, 'go fishing': 4, 'study abroad': 4, 'buy flowers': 4, 'ask for direction': 4, 'crime': 4, 'exhibition': 4, 'ailment': 4, 'blame': 4, 'TV programs': 4, 'business conversation': 4, 'in a restaurant': 4, 'ask some questions': 4, 'a business trip': 4, 'time difference': 4, 'palmistry': 4, 'Social Meeting': 4, 'swimming': 4, 'proposal': 4, 'bus': 4, 'late for class': 4, 'computer problem': 4, 'at a restaurant': 4, 'library service': 4, 'order drinks': 4, 'English': 4, 'order the meal': 4, 'resume': 4, 'traveling': 4, 'project': 4, 'summer job': 4, 'taxi service': 4, 'buy a hat': 4, 'bike': 4, 'burglary': 4, 'change a job': 4, 'eating habits': 4, 'delivery': 4, 'old music box': 4, 'practice English': 4, 'cafeteria': 4, 'a job': 4, 'go to school': 4, 'on the plane': 4, 'congratulations': 4, 'pets': 4, 'cash the check': 4, 'housework': 4, 'Hobbies': 4, 'washing machine': 4, 'job description': 4, 'fall in love': 4, 'go camping': 4, 'bargaining': 4, 'complaints': 4, 'a car accident': 4, 'drinks': 4, 'birthday celebration': 4, 'exam': 4, 'hunt a job': 4, 'doctor interrogation': 4, 'necklace': 4, 'deposit money': 4, 'seeing a doctor': 4, 'talk about someone': 3, 'train': 3, 'busy schedule': 3, 'order breakfast': 3, 'souvenirs': 3, 'renting problem': 3, 'washing clothes': 3, 'son': 3, 'pay the check': 3, 'persuade someone': 3, 'late for dinner': 3, 'work plan': 3, 'direction': 3, 'lose a wallet': 3, 'gym': 3, 'eat out': 3, 'praise': 3, 'work talk': 3, 'history': 3, 'hot weather': 3, 'letter': 3, 'redecorate the house': 3, 'neighborhood': 3, 'flat': 3, 'make a deal': 3, 'customs inspection': 3, 'buy a TV': 3, 'animals': 3, 'buy a refrigerator': 3, 'new project': 3, 'change money': 3, 'connecting flight': 3, 'Internet': 3, 'welcome': 3, 'post-sales service': 3, 'buy roses': 3, 'new school life': 3, 'dressing': 3, 'car problems': 3, 'apartment renting': 3, 'Work': 3, 'space and cosmos': 3, 'healthy eating': 3, 'get up': 3, 'retirement plan': 3, 'in the library': 3, 'Renting': 3, 'neighbour': 3, 'earthquake': 3, 'furniture': 3, 'airsickness': 3, 'relax': 3, 'job change': 3, 'car': 3, 'warning': 3, 'Break up': 3, 'booking a room': 3, 'service charge': 3, 'a company': 3, 'wedding anniversary': 3, 'work experience': 3, 'noise': 3, 'to the airport': 3, 'discuss transportation': 3, 'coffee shop': 3, 'see a dentist': 3, 'game': 3, 'working schedule': 3, 'appearance description': 3, 'confession': 3, 'market': 3, 'public transportation': 3, 'newspaper': 3, 'buying shoes': 3, 'Reservation': 3, 'political party': 3, 'sickness': 3, 'volunteer work': 3, 'air pollution': 3, 'happiness': 3, 'baseball game': 3, 'wedding preparation': 3, 'flight reservation': 3, 'big family': 3, 'weekend plans': 3, 'painting': 3, 'family member talk': 3, 'catering service': 3, 'sell the house': 3, 'friends': 3, 'paycheck': 3, 'tour recommendation': 3, 'sending a package': 3, 'letters': 3, 'wife': 3, 'jobs': 3, 'a letter': 3, 'new suit': 3, 'bus route': 3, 'conversation with doctor': 3, 'relationship predicaments': 3, 'cultural differences': 3, 'go home': 3, 'stop smoking': 3, 'system upgrade': 3, 'do sports': 3, 'direct the way': 3, 'raise': 3, 'join a club': 3, 'homework': 3, 'spicy food': 3, 'taxi talk': 3, 'blackout': 3, 'course': 3, 'religion': 3, 'skiing': 3, 'luggage': 3, 'coat': 3, 'a phone call': 3, 'ticket service': 3, 'visit a patient': 3, 'go to airport': 3, 'summer vacation plan': 3, 'dress code': 3, 'love story': 3, 'repair a car': 3, 'work schedule': 3, 'car parking': 3, 'curfew': 3, 'life experience': 3, 'doing exercise': 3, 'reasons for lateness': 3, 'crowded bus': 3, 'family talk': 3, 'future career': 3, 'birthday party preparation': 3, 'mountain climbing': 3, 'look for an apartment': 3, 'a job application': 3, 'hall pass': 3, 'green life': 3, 'miss the stop': 3, 'insomnia': 3, 'girl': 3, 'money exchange': 3, 'office supplies': 3, 'healthy lifestyle': 3, 'get lost': 3, 'read a book': 3, 'booking tickets': 3, 'a birthday gift': 3, 'buying a gift': 3, 'internet': 3, 'life skills': 3, 'ask for the way': 3, 'hiking': 3, 'have a meal': 3, 'expected salary': 3, 'borrow the car': 3, 'trip to Paris': 3, 'cable': 3, 'anniversary': 3, 'describe a person': 3, 'a job interview': 3, 'pay raise': 3, 'New car': 3, 'repair a computer': 3, 'going to London': 3, 'shooting': 3, 'childbirth': 3, 'deposit': 3, 'English songs': 3, 'take pictures': 3, 'flight information': 3, 'birthday present': 3, 'book a flight': 3, 'bicycle': 3, 'greet each other': 3, 'deal': 3, 'lose a job': 3, 'goodbye': 3, 'play a game': 3, 'buy a sweater': 3, 'ideal home': 3, 'decision': 3, 'fashion': 3, 'physical examination': 3, 'clean the house': 3, 'getting lost': 3, 'grandmother': 3, 'basketball': 3, 'car repair': 3, 'joke': 3, 'airport security': 3, 'Party': 3, 'order a meal': 3, 'sick': 3, 'vocation': 3, 'breaking up': 3, 'catch the train': 3, 'have a cold': 3, 'music preference': 3, 'ticket booking': 3, 'discuss the salary': 3, 'countries': 3, 'business plan': 3, 'go hiking': 3, 'children': 3, 'see off': 3, 'winter': 3, 'boarding': 3, 'cook': 3, 'sing a song': 3, 'lunch invitation': 3, 'loan application': 3, 'room': 3, 'pet': 3, 'airport pickup': 3, 'course enrollment': 3, 'climb the mountain': 3, 'agreement': 3, 'new teacher': 3, 'museum': 3, 'lost and found': 3, 'business cards': 3, 'a vacation': 3, 'cheer up': 3, 'Plans': 3, 'career plan': 3, 'library card': 3, 'hang out': 3, 'meat shopping': 3, 'checking out': 3, 'night life': 3, 'inquiry': 3, 'pay a visit': 3, 'see the apartment': 3, 'Taking order': 3, 'go skiing': 3, 'climate': 3, 'buy furniture': 3, 'a bad cold': 3, 'parcel': 3, 'home inspection': 3, 'bank': 3, 'clothes': 3, 'tickets': 3, 'commuting': 3, 'give a ticket': 3, 'family conversation': 3, 'weekend activity': 3, 'environment problems': 3, 'picnic preparation': 3, 'buy meat': 3, 'learning Chinese': 3, 'buy tickets': 3, 'waiting': 3, 'dance invitation': 3, 'health': 3, 'police': 3, 'dinner preparation': 3, 'surprise': 3, 'language learning': 3, 'use the ATM': 3, 'headache': 3, 'watch': 3, 'ask a question': 3, 'traveling plan': 3, 'airport service': 2, 'New York': 2, 'reach an agreement': 2, 'pick up someone': 2, 'sightseeing': 2, 'find a memo': 2, 'beauty parlor': 2, 'cleaning': 2, 'bachelor party': 2, 'renovate the house': 2, 'picnic invitation': 2, 'Customs declaration': 2, 'auction': 2, 'go bowling': 2, 'go to bed': 2, 'a bar': 2, 'wake-up call': 2, 'leave the job': 2, 'pen pal': 2, 'summer course': 2, 'luggage service': 2, 'a doctor': 2, 'sleeping problems': 2, 'ordering dishes': 2, 'drama': 2, 'cooperation': 2, 'cook dinner': 2, 'at the customs': 2, 'registration': 2, 'natural disaster': 2, 'Chinese': 2, 'supper': 2, 'study English': 2, 'get hurt': 2, 'test': 2, 'the first word': 2, 'workplace': 2, 'galaxies': 2, 'cleaning ladies': 2, 'car repairment': 2, 'take an order': 2, 'bakery': 2, 'school time': 2, 'technology': 2, 'take medicine': 2, 'car service': 2, 'buy a watch': 2, 'friendship': 2, 'air ticket': 2, 'a birthday present': 2, 'phased retirement': 2, 'make excuses': 2, 'post office': 2, 'stolen bag': 2, 'New roommate': 2, 'trip planning': 2, 'war': 2, 'plastic surgery': 2, 'Check in': 2, 'prepare dinner': 2, 'plan a party': 2, 'photographer': 2, 'cut hair': 2, 'aging problem': 2, 'trains': 2, 'go to concert': 2, 'take a walk': 2, 'discuss weather': 2, 'public order': 2, 'get off': 2, 'review': 2, 'students welfare club': 2, 'foreign language': 2, 'socks': 2, 'share news': 2, 'celebrate birthday': 2, 'dinner arrangement': 2, 'second-hand goods discussion': 2, 'artist': 2, 'see an apartment': 2, 'fire': 2, 'table': 2, 'at the bar': 2, 'change': 2, 'steamed crabs': 2, 'pay by check': 2, 'change job': 2, 'theft': 2, 'package delivery': 2, 'family member': 2, 'basketball game': 2, 'making a suit': 2, 'live in village': 2, 'a quarrel': 2, 'crush': 2, 'education': 2, 'summer holiday': 2, 'college life': 2, 'go on a diet': 2, 'food preparation': 2, 'trip experience': 2, 'boring meeting': 2, 'late': 2, 'have a baby': 2, 'casual conversation': 2, 'bags': 2, 'remit money': 2, 'exchange money': 2, 'passing customs': 2, 'cockroaches': 2, 'job searching': 2, 'worry about someone': 2, 'business cooperation': 2, 'buy a book': 2, 'cancel a check': 2, 'plans': 2, 'games': 2, 'Conference': 2, 'a safe box': 2, 'choose courses': 2, 'triplets': 2, 'scam website': 2, 'spy': 2, 'the first meeting': 2, "teacher's request": 2, 'animal protection': 2, 'shipment': 2, 'book discussion': 2, 'rent a room': 2, 'procrastination': 2, 'White Day': 2, 'cycle tour': 2, 'bowling': 2, 'a gift': 2, 'buy ticket': 2, 'fees': 2, 'time schedule': 2, 'book flight tickets': 2, 'autograph': 2, 'blog': 2, 'refuse the invitation': 2, 'novel': 2, 'rent the apartment': 2, 'having breakfast': 2, 'plan for tonight': 2, 'car wash package': 2, 'order a suit': 2, 'internet business': 2, 'choose a university': 2, 'new shirt': 2, 'cancel the reservation': 2, 'a marriage': 2, 'dreams': 2, 'do housework': 2, 'buy food': 2, 'school day': 2, 'telephone conversation': 2, 'cold weather': 2, 'communication skills': 2, 'basketball match': 2, 'net love': 2, 'punishment in college': 2, 'social communication': 2, 'settle the bill': 2, 'in hospital': 2, 'individual impression': 2, 'China': 2, 'blind date': 2, 'passport': 2, 'what to buy': 2, 'room registeration': 2, 'old friends': 2, 'consultation': 2, 'being cheated': 2, 'a course': 2, 'fashion magazine': 2, 'independence': 2, 'change size': 2, 'entrant': 2, 'graduation': 2, 'work interview': 2, 'schedule a meeting': 2, 'buying a car': 2, 'regret': 2, 'close the account': 2, 'noisy office': 2, 'amusement park': 2, 'plane reservation': 2, 'learning languages': 2, 'selecting gift': 2, "at the barber's": 2, 'at the airport': 2, 'machine': 2, 'training course': 2, 'health problems': 2, 'report': 2, 'traffic rules regulation': 2, 'buying a phone': 2, 'school dance': 2, 'recommendation letter': 2, 'grown-up children': 2, 'Japan': 2, 'one-year anniversary': 2, 'social greeting talk': 2, 'buy sunglasses': 2, 'jet lag': 2, 'cheating': 2, 'housekeeping': 2, 'working overtime': 2, 'first meeting': 2, 'stay up': 2, 'notice': 2, 'information overload': 2, 'ordering the food': 2, 'buying tickets': 2, 'weekend camping trip': 2, 'table reservation': 2, 'movie choice': 2, 'accommodation': 2, 'bargain market': 2, 'cell phone': 2, 'learn to drive': 2, 'own room': 2, 'vegetarian': 2, 'magazine': 2, 'a new girl': 2, 'daily routine': 2, 'surprising news': 2, 'sport': 2, 'decorate the house': 2, 'luncheon meeting': 2, 'car reservation': 2, 'write a resume': 2, 'computer games': 2, 'chase a girl': 2, 'holiday experience': 2, 'trip to England': 2, 'wedding invitation': 2, 'public transport': 2, 'taxi conversation': 2, 'smoke': 2, 'piano class': 2, 'Library service': 2, 'budget': 2, 'water the garden': 2, 'sign a contract': 2, 'product': 2, 'Thanksgiving cooking': 2, 'weather report': 2, 'safety manual': 2, 'use a computer': 2, 'new computer': 2, 'eating out': 2, 'ticket': 2, 'emergency call': 2, 'a movie': 2, 'entertainment': 2, 'country': 2, 'taxi ride': 2, 'football game': 2, 'body language': 2, 'treatment': 2, 'buy a farm': 2, 'job opportunity': 2, 'discuss an apartment': 2, 'job promotion': 2, 'traffic tools': 2, 'paper proofread': 2, 'flight cancellation': 2, 'job chance': 2, 'discuss music': 2, 'buying a pan': 2, 'teamwork': 2, 'salary increase': 2, 'band forming': 2, 'drive to London': 2, 'job-hunting': 2, 'fast food': 2, 'family members': 2, 'tell a story': 2, 'take a break': 2, 'go out': 2, 'go to China': 2, 'fear of heights': 2, 'garden': 2, 'new laptop': 2, 'environment': 2, 'improve English': 2, "puppies' care": 2, 'mistaken identity': 2, 'investment discussion': 2, 'withdraw the money': 2, 'sweater': 2, "doctor's advice": 2, 'make decisions': 2, 'holiday time': 2, 'meeting time': 2, 'opera': 2, 'asks for directions': 2, 'Birthday Surprise': 2, 'take the temperature': 2, 'film review': 2, 'summer and winter': 2, 'house introduction': 2, 'change a seat': 2, 'floods': 2, 'settle the account': 2, 'opening an account': 2, 'make friends': 2, 'textbooks': 2, 'get a promotion': 2, 'ask admission requirements': 2, 'mother': 2, 'investigation': 2, 'mistake': 2, 'checking in': 2, 'hotel check in': 2, 'birthday party invitation': 2, 'Christmas party': 2, 'leave early': 2, 'account': 2, 'chicken pox': 2, 'order dessert': 2, 'change the appointment': 2, 'time management': 2, 'draw the blood': 2, 'get a raise': 2, 'communication strategy': 2, 'a bus tour': 2, 'Part-time job': 2, 'play musical instruments': 2, 'a new neighbor': 2, 'sign an agreement': 2, 'develop a film': 2, 'seeing doctor': 2, 'great pressure': 2, 'geography': 2, 'raise money': 2, 'buy cosmetics': 2, 'look for someone': 2, 'package tour': 2, 'summer vocation': 2, 'place an order': 2, 'stealing': 2, 'weather and season': 2, 'live with parents': 2, 'birthday surprise': 2, 'tourist attractions': 2, 'school choice': 2, 'do exercise': 2, 'make a choice': 2, 'job interview preparation': 2, 'a dress': 2, 'popular sports': 2, 'buy a phone': 2, 'house price': 2, 'work abroad': 2, 'language change': 2, 'appreciation': 2, 'dining at restaurants': 2, 'booking a trip': 2, 'cities': 2, 'buy a desk': 2, 'book a taxi': 2, 'buy lingerie': 2, 'Western food': 2, 'see the house': 2, 'happy birthday': 2, 'buy a table': 2, 'travelling': 2, 'a party': 2, 'offering help': 2, 'guide a tour': 2, 'a new suit': 2, 'purchase': 2, 'art': 2, 'unemployment benefits': 2, 'ski': 2, 'hotel check-in': 2, 'a project': 2, 'catch the plane': 2, 'a conference': 2, 'tell the truth': 2, 'store': 2, 'favourite season': 2, 'Train': 2, 'prepare a presentation': 2, 'buy a camera': 2, 'food choice': 2, 'work feelings': 2, 'go home late': 2, 'late for appointment': 2, 'salary raise': 2, 'Travel': 2, 'go Dutch': 2, 'discuss swimming': 2, 'work together': 2, 'ATM accident': 2, 'go in Dutch': 2, 'water pollution': 2, 'have a talk': 2, 'lunch meeting': 2, 'school transfer': 2, 'English 

In [ ]:
# Remove columns 'id', 'index', and 'topics'
ds['train'] = ds['train'].remove_columns(['id', 'index', 'topic'])

# Preproccesing Without Tokenization

### Preprocssing Functions

In [ ]:
import re
#removing those parts instead of replacing them with tags (<url> or <number>)
#because it is more fitting for summarization

In [ ]:
#remove urls because we wont need it for summarization
def remove_urls(text):
    return re.sub(r'https?:\/\/.*[\r\n\s]*', '', text, flags=re.MULTILINE)

In [ ]:
#normalize to lower case
def lower_case(text):
    return ''.join([w.lower() for w in text])

In [ ]:
##remove Email because we wont need it for summarization
def remove_email(text):
    return re.sub(r'\S*@\S*\s?', '', text, flags=re.MULTILINE)

In [ ]:
# remove tags because we wont need it for summarization
def remove_tags(text):
    # Remove tags like <file_photo>, <file_gif>, etc.
    text = re.sub(r'<[^>]+>', '', text)
    return text

In [ ]:
##remove english because we want the text to be arabic
def remove_english_characters(text):
    # Remove all English alphabetic characters (both uppercase and lowercase)
    text = re.sub(r'[A-Za-z]', '', text)
    return text

In [ ]:
#stem both the input and the output

from nltk.stem import SnowballStemmer

s_stemmer = SnowballStemmer('arabic')

In [ ]:
#remove the new line and tags that are not needed
def normalize(text):
    text = text.replace('\n', '')
    text = text.replace('\r', ' ')
    text = text.replace('\t', ' ')
    text = text.replace('+', ' ')
    return text

In [ ]:
def normalize_arabic(text):
    # Remove diacritics
    diacritics = re.compile(r'[\u064B-\u065F]')
    text = re.sub(diacritics, '', text)
    # Normalize letters
    text = re.sub(r'[إأآا]', 'ا', text)
    text = re.sub(r'ى', 'ي', text)
    text = re.sub(r'ؤ', 'و', text)
    text = re.sub(r'ئ', 'ي', text)
    # Remove tatweel
    text = re.sub(r'ـ', '', text)
    return text

In [ ]:
def clean_text(text):
    text = re.sub(r'\s+', ' ', text)    # Remove extra spaces
    return text

In [ ]:
def preprocess_text(text):
    text = remove_urls(text)
    text = remove_email(text)
    text = remove_tags(text)
    text = remove_english_characters(text)
    text = normalize(text)
    text = lower_case(text)
    normalize_arabic(text)
    clean_text(text)
    # text = stem_text(text)
    return text
    #won't stem now will stem after tokenization

In [ ]:
print(type(ds["train"]["dialogue"]))

<class 'datasets.arrow_dataset.Column'>

In [ ]:
ds["train"] = ds["train"].map(lambda example: {"dialogue_processed": preprocess_text(example["dialogue"])})

Map:   0%|          | 0/24813 [00:00<?, ? examples/s]

In [ ]:
ds["train"]["dialogue_processed"]

Column(['أوبرا: خمن ما أعطانيه جو ليومبي نايجل: الجوارب؟ ميني: هزة الجماع؟ أوبرا:  أوبرا: يا رفاق هم الأسوأ نايجل: لول ميني: كنت على حق نوعا ما أوبرا: أردت أن أذهب إلى هناك بشدة نايجل: إذن اشترى لك الطعام؟ أوبرا: إنه ليس مجرد طعام أوبرا: هذه هي الحلويات المفضلة لدي من تركيا ميني: لا أحصل على حبك للطعام ولكن كل ما يجعلك سعيدًا نايجل: ألا تعاني من حساسية من المكسرات؟ أوبرا: أنا حساسية من الجوز والكاجو ، لذا فلا بأس ميني: تبدو لطيفة جدا نايجل: حسنًا أوبرا: لديها أيضًا بتلات وردية نايجل: تبدو لذيذة', 'إيليا: مهلا ، في طريقي إلى المكتب.هل يمكنك أن ترسل لي هذا جدول الأعمال لهذا اليوم؟ بريت: بالتأكيد.إنه جاهز فقط إيليا: شكرا.هل كيتلين هناك حتى الآن؟ بريت: لا ، ليس بعد إيليا: حسنًا ، فقط أتساءل.لدينا مكالمة جماعية في التاسعة. بريت: هل هذا مع مؤسسة الكرم؟ إيليا: نعم ، إنهم يفكرون في طلب المنح لدينا ، لكنهم أرادوا إجراء مقابلة معنا أولاً بريت: حسنًا ، حظًا سعيدًا في ذلك إيليا: شكرا. بريت: أرسل للتو جدول أعمال. إيليا: حسنًا.سأخبرك عندما أحصل عليه.هل يمكنك التحقق مما إذا كان مارتن هناك؟أنا بحاجة إلى رد على بريد إلكتروني أرسلته إليه بريت: إنه على الهاتف ، لكنني سأتحدث معه في أقرب وقت إيليا: شكرا.ذكّرني: هل حفلة عيد الميلاد غدًا؟ بريت: تم تأجيله إلى الخميس.أرسلنا سكوت جميعًا تحديثًا. إيليا: هذا صحيح.لا أعرف أين كانت عقلي هذا الأسبوع بريت: أعتقد أنني أسمع مارتن يختتم دعوته الآن. إيليا: حسنًا ، عظيم. بريت: تحدثت معه للتو.إنه يرسل لك البريد الإلكتروني الآن إيليا: شكرا رجل.فقط حصلت على جدول الأعمال أيضا.سأراك قليلا. بريت: أراك قليلا', 'الشخص 1: ما رأيك في شركتنا؟  الشخص 2: أنت الشركة الرائدة في صناعة الكمبيوتر.  الشخص 1: لماذا تعتقد ذلك؟  الشخص 2: أولاً ، حصتك الساحقة في السوق العالمية.ثانياً ، تفوقك في المبيعات والأرباح بالإضافة إلى مقدار رأس المال وعدد الموظفين.ثالثًا ، التنوع في خط الإنتاج الخاص بك لا يعلى عليه.  الشخص 1: في أي عمل تهتم به في هذه المنظمة؟  الشخص 2: على وجه الخصوص ، أنا مهتم بالتسويق في المجال المحلي.', 'كلوي: ص. باتريشيا: ... كلوي: مم ، طيب ، ليلة صعبة: د باتريشيا: ما زلت في السرير باتريشيا: لكني بحاجة حقًا إلى الماء باتريشيا: وهي بعيدة جدًا كلوي: على الأقل أنت في مزاج جيد ؛) باتريشيا: جيد كما يحصل كلوي: هل حصلت على رقم هذا الرجل؟ باتريشيا: نعم ، فعلت. كلوي: و ...؟ كلوي: هل أعطيته لك؟ باتريشيا: أنت مجنون؟أنا لا أعطي رقمي للرجال العشوائيين كلوي: حتى اللطيف؟؛) باتريشيا: هاهاها ، قد لا تكون لطيفة للغاية عندما تكون رصينًا كلوي: هيا ، لم أكن في حالة سكر حتى تتمكن من الاعتماد على تقديري ؛) كلوي: هل ستتصل به رغم ذلك؟ باتريشيا: لا أعرف بعد ، بالتأكيد ليس الآن كلوي: حسنًا ، بالطبع ليس الآن ، ولكن بشكل عام باتريشيا: ربما لا', 'الشخص 1: ماذا تفعل يا أمي؟  الشخص 2: أحصل على شيء جاهز للغد.غدا هو يوم تروي.  الشخص 1: يوم زرع الأشجار؟ماذا يفعل الناس في هذا اليوم يا أمي؟  الشخص 2: كثير من الناس سيذهبون ويزرعون الأشجار.  الشخص 1: لماذا يفعلون ذلك؟  الشخص 2: لجعل الأرض أكثر جمالا.وجعل حياتنا أفضل.  الشخص 1: لكنني غالبًا ما أرى أشخاصًا على شاشة التلفزيون يقطعون العديد من الأشجار الكبيرة.لماذا يفعلون ذلك يا أمي؟  الشخص 2:  ، لصنع الورق والمنازل وجعل حياتنا أفضل.  الشخص 1: لجعل حياتنا أفضل أيضًا؟أنا فقط لا أفهم.أمي ، لماذا يذهب الكثير من الناس وزراعة الأشجار في نفس اليوم؟  الشخص 2: أوه ، ابني العزيز.من الصعب أن تشرح لك.عندما تكبر ، سوف تفهم.فقط تذكر أن الأشجار مهمة جدا بالنسبة لنا.'])

In [ ]:
ds["train"] = ds["train"].map(lambda example: {"summary_processed": preprocess_text(example["summary"])})

Map:   0%|          | 0/24813 [00:00<?, ? examples/s]

In [ ]:
ds["train"]["dialogue"][50]

'جوانا: يرسلون رسائل بريد إلكتروني حول ليفاندوفسكا.\n ميرف: ماذا حدث؟\n جوانا: <file_photo>\n ميرف: ووو!\n جوانا: تم نقلها إلى المستشفى لأنها تعاني من الحصبة.\n ميرف: كان لديها ماذا؟\n جوانا: يجب على أي شخص لديه اتصال معها خلال اليومين الماضيين تلقيح.\n ميرف: لحسن الحظ لم أرها منذ الفصل الدراسي الأخير ...\n جوانا: فعلت ، هي معلمتي أطروحة :(\n ميرف: ماذا ستفعل؟\n جوانا: إنهم ينظمون اللقاحات في المبنى الرئيسي من 17 حتى التاسع عشر.\n ميرف: عليك أن تذهب!\n جوانا: أعرف ... وبدأت للتو العمل ، لذا ليس لدي الكثير من الوقت.\n ميرف: هيا ، هذا مهم حقا.\n جوانا: سأحاول القيام بذلك قبل العمل في الثامنة عشرة ، وآمل ألا أفقد اليوم بأكمله ...'

In [ ]:
ds["train"]["dialogue_processed"][50]

'جوانا: يرسلون رسائل بريد إلكتروني حول ليفاندوفسكا. ميرف: ماذا حدث؟ جوانا:  ميرف: ووو! جوانا: تم نقلها إلى المستشفى لأنها تعاني من الحصبة. ميرف: كان لديها ماذا؟ جوانا: يجب على أي شخص لديه اتصال معها خلال اليومين الماضيين تلقيح. ميرف: لحسن الحظ لم أرها منذ الفصل الدراسي الأخير ... جوانا: فعلت ، هي معلمتي أطروحة :( ميرف: ماذا ستفعل؟ جوانا: إنهم ينظمون اللقاحات في المبنى الرئيسي من 17 حتى التاسع عشر. ميرف: عليك أن تذهب! جوانا: أعرف ... وبدأت للتو العمل ، لذا ليس لدي الكثير من الوقت. ميرف: هيا ، هذا مهم حقا. جوانا: سأحاول القيام بذلك قبل العمل في الثامنة عشرة ، وآمل ألا أفقد اليوم بأكمله ...'

In [ ]:
ds["train"]["summary"][50]

'ليفاندوفسكا لديه الحصبة.هناك لقاحات في المبنى الرئيسي من 17 حتى التاسع عشر لكل من كان على اتصال معها.'

In [ ]:
ds["train"]["summary_processed"][50]

'ليفاندوفسكا لديه الحصبة.هناك لقاحات في المبنى الرئيسي من 17 حتى التاسع عشر لكل من كان على اتصال معها.'

In [ ]:
## we wont remomve punc or numbers because that will be helpful for us in the training process
#keep for now use if needed
def remove_punc(text):
   return  re.sub(r'[^\w\s]', ' ', text, flags=re.MULTILINE)

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
# we will keep the stop words in this case because they are immportant in terms of summarization ,
#we would remove them if it was about emotion analysis
from nltk.corpus import stopwords
ar_stop_words = set(stopwords.words("arabic"))

# Expriments for Lemmatization and Stemming

###First Tokenization than stemming

In [ ]:
from nltk.tokenize import WordPunctTokenizer
tokenizer = WordPunctTokenizer()
#tokenizer.tokenize()

In [ ]:
ds["train"] = ds["train"].map(lambda example: {"dialogue_processed_tokenized":  tokenizer.tokenize(example["dialogue_processed"])})

Map:   0%|          | 0/24813 [00:00<?, ? examples/s]

In [ ]:
ds["train"] = ds["train"].map(lambda example: {"summary_processed_tokenized":  tokenizer.tokenize(example["summary_processed"])})

Map:   0%|          | 0/24813 [00:00<?, ? examples/s]

In [ ]:
ds["train"]["dialogue_processed_tokenized"][50]

['جوانا',
 ':',
 'يرسلون',
 'رسائل',
 'بريد',
 'إلكتروني',
 'حول',
 'ليفاندوفسكا',
 '.',
 'ميرف',
 ':',
 'ماذا',
 'حدث',
 '؟',
 'جوانا',
 ':',
 'ميرف',
 ':',
 'ووو',
 '!',
 'جوانا',
 ':',
 'تم',
 'نقلها',
 'إلى',
 'المستشفى',
 'لأنها',
 'تعاني',
 'من',
 'الحصبة',
 '.',
 'ميرف',
 ':',
 'كان',
 'لديها',
 'ماذا',
 '؟',
 'جوانا',
 ':',
 'يجب',
 'على',
 'أي',
 'شخص',
 'لديه',
 'اتصال',
 'معها',
 'خلال',
 'اليومين',
 'الماضيين',
 'تلقيح',
 '.',
 'ميرف',
 ':',
 'لحسن',
 'الحظ',
 'لم',
 'أرها',
 'منذ',
 'الفصل',
 'الدراسي',
 'الأخير',
 '...',
 'جوانا',
 ':',
 'فعلت',
 '،',
 'هي',
 'معلمتي',
 'أطروحة',
 ':(',
 'ميرف',
 ':',
 'ماذا',
 'ستفعل',
 '؟',
 'جوانا',
 ':',
 'إنهم',
 'ينظمون',
 'اللقاحات',
 'في',
 'المبنى',
 'الرئيسي',
 'من',
 '17',
 'حتى',
 'التاسع',
 'عشر',
 '.',
 'ميرف',
 ':',
 'عليك',
 'أن',
 'تذهب',
 '!',
 'جوانا',
 ':',
 'أعرف',
 '...',
 'وبدأت',
 'للتو',
 'العمل',
 '،',
 'لذا',
 'ليس',
 'لدي',
 'الكثير',
 'من',
 'الوقت',
 '.',
 'ميرف',
 ':',
 'هيا',
 '،',
 'هذا',
 'مهم',
 'حقا',
 '.',
 'جوانا',
 ':',
 'سأحاول',
 'القيام',
 'بذلك',
 'قبل',
 'العمل',
 'في',
 'الثامنة',
 'عشرة',
 '،',
 'وآمل',
 'ألا',
 'أفقد',
 'اليوم',
 'بأكمله',
 '...']

In [ ]:
ds["train"]["summary_processed_tokenized"][50]

['ليفاندوفسكا',
 'لديه',
 'الحصبة',
 '.',
 'هناك',
 'لقاحات',
 'في',
 'المبنى',
 'الرئيسي',
 'من',
 '17',
 'حتى',
 'التاسع',
 'عشر',
 'لكل',
 'من',
 'كان',
 'على',
 'اتصال',
 'معها',
 '.']

In [ ]:
from nltk.stem import SnowballStemmer

s_stemmer = SnowballStemmer('arabic')

print(s_stemmer.stem('كرهتهم'))
print(s_stemmer.stem('إعلاميون'))
print(s_stemmer.stem('جامعات'))

كره
اعلام
جامع

In [ ]:
ds["train"] = ds["train"].map(lambda example: {"dialogue_processed_tokenized_stemmed": " ".join([s_stemmer.stem(token) for token in example["dialogue_processed_tokenized"]])})

Map:   0%|          | 0/24813 [00:00<?, ? examples/s]

In [ ]:
ds["train"] = ds["train"].map(lambda example: {"summary_processed_tokenized_stemmed": " ".join([s_stemmer.stem(token) for token in example["summary_processed_tokenized"]])})

Map:   0%|          | 0/24813 [00:00<?, ? examples/s]

In [ ]:
ds["train"]["dialogue_processed_tokenized_stemmed"][50]

'جوا : يرسل رسايل ريد الكتر حول يفاندوفس . ميرف : ماذ حدث  جوا : ميرف : ووو ! جوا : تم نقل الى مستشفى لان تعا من حصب . ميرف : كان لد ماذ  جوا : يجب على أي شخص لد اتصال معه خلال يوم ماض تلقيح . ميرف : لحس الحظ لم اره منذ فصل دراس اخير ... جوا : فعل  هي معل اطروح :( ميرف : ماذ ستفعل  جوا : انهم ينظم لقاح في مبنى رييس من 17 حتى تاسع عشر . ميرف : عل أن تذهب ! جوا : اعرف ... بدء للتو عمل  لذا ليس لد كثير من الو . ميرف : هيا  هذا مهم حقا . جوا : ساحاول قيام بذل قبل عمل في ثامن عشر  امل الا افقد يوم اكمل ...'

In [ ]:
ds["train"]["summary_processed_tokenized_stemmed"][50]

'يفاندوفس لد حصب . هنا لقاح في مبنى رييس من 17 حتى تاسع عشر لكل من كان على اتصال معه .'

###First Tokenization than Lemmataization

In [ ]:
pip install qalsadi

Collecting qalsadi
  Downloading qalsadi-0.5.1-py3-none-any.whl.metadata (14 kB)
Collecting Arabic-Stopwords>=0.4.2 (from qalsadi)
  Downloading Arabic_Stopwords-0.4.3-py3-none-any.whl.metadata (8.9 kB)
Collecting alyahmor>=0.2 (from qalsadi)
  Downloading alyahmor-0.2-py3-none-any.whl.metadata (11 kB)
Collecting arramooz-pysqlite>=0.4.2 (from qalsadi)
  Downloading arramooz_pysqlite-0.4.2-py3-none-any.whl.metadata (4.0 kB)
Collecting codernitydb3 (from qalsadi)
  Downloading codernitydb3-0.6.0.tar.gz (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.1/46.1 kB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting libqutrub>=1.2.3 (from qalsadi)
  Downloading libqutrub-1.2.4.1-py3-none-any.whl.metadata (7.5 kB)
Collecting mysam-tagmanager>=0.4.1 (from qalsadi)
  Downloading mysam_tagmanager-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting naftawayh>=0.3 (from qalsadi)
  Downloading Naftawayh-0.4-py3-none-any.whl.metadata (8.7 kB)
Collecting pickledb>=0.9.2 (from qalsadi)
  Downloading pickledb-1.4.1.1-py3-none-any.whl.metadata (1.4 kB)
Collecting pyarabic>=0.6.7 (from qalsadi)
  Downloading PyArabic-0.6.15-py3-none-any.whl.metadata (10 kB)
Collecting tashaphyne>=0.3.4.1 (from qalsadi)
  Downloading Tashaphyne-0.3.6-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: orjson>=3.11.5 in /usr/local/lib/python3.12/dist-packages (from pickledb>=0.9.2->qalsadi) (3.11.5)
Collecting aiofiles>=25.1.0 (from pickledb>=0.9.2->qalsadi)
  Downloading aiofiles-25.1.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from pyarabic>=0.6.7->qalsadi) (1.17.0)
Downloading qalsadi-0.5.1-py3-none-any.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.5/268.5 kB 14.5 MB/s eta 0:00:00
Downloading alyahmor-0.2-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.1/65.1 kB 7.7 MB/s eta 0:00:00
Downloading Arabic_Stopwords-0.4.3-py3-none-any.whl (360 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 360.5/360.5 kB 24.3 MB/s eta 0:00:00
Downloading arramooz_pysqlite-0.4.2-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 17.4 MB/s eta 0:00:00
Downloading libqutrub-1.2.4.1-py3-none-any.whl (138 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.0/139.0 kB 12.4 MB/s eta 0:00:00
Downloading mysam_tagmanager-0.4.1-py3-none-any.whl (37 kB)
Downloading Naftawayh-0.4-py3-none-any.whl (332 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 332.6/332.6 kB 32.5 MB/s eta 0:00:00
Downloading pickledb-1.4.1.1-py3-none-any.whl (3.4 kB)
Downloading PyArabic-0.6.15-py3-none-any.whl (126 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.4/126.4 kB 8.9 MB/s eta 0:00:00
Downloading Tashaphyne-0.3.6-py3-none-any.whl (251 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.5/251.5 kB 18.9 MB/s eta 0:00:00
Downloading aiofiles-25.1.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: codernitydb3
  Building wheel for codernitydb3 (setup.py) ... done
  Created wheel for codernitydb3: filename=codernitydb3-0.6.0-py3-none-any.whl size=59852 sha256=407beb8db296fbbdd793b8f1f6f835e8076ae59256b460f7e56e2d4ee3cd2492
  Stored in directory: /root/.cache/pip/wheels/44/e9/b4/5bf3e5eab010973a62fb02bfde9ae3a41672b16d244cc2e2df
Successfully built codernitydb3
Installing collected packages: mysam-tagmanager, pyarabic, codernitydb3, aiofiles, tashaphyne, pickledb, libqutrub, arramooz-pysqlite, Arabic-Stopwords, naftawayh, alyahmor, qalsadi
  Attempting uninstall: aiofiles
    Found existing installation: aiofiles 24.1.0
    Uninstalling aiofiles-24.1.0:
      Successfully uninstalled aiofiles-24.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 5.50.0 requires aiofiles<25.0,>=22.0, but you have aiofiles 25.1.0 which is incompatible.
Successfully installed Arabic-Stopwords-0.4.3 aiofiles-25.1.0 alyahmor-0.2 arramooz-pysqlite-0.4.2 codernitydb3-0.6.0 libqutrub-1.2.4.1 mysam-tagmanager-0.4.1 naftawayh-0.4 pickledb-1.4.1.1 pyarabic-0.6.15 qalsadi-0.5.1 tashaphyne-0.3.6

In [ ]:
import qalsadi.lemmatizer
text = u"""هل تحتاج إلى ترجمة كي تفهم خطاب الملك؟ اللغة "الكلاسيكية" (الفصحى) موجودة في كل اللغات وكذلك اللغة "الدارجة" .. الفرنسية التي ندرس في المدرسة ليست الفرنسية التي يستخدمها الناس في شوارع باريس .. وملكة بريطانيا لا تخطب بلغة شوارع لندن .. لكل مقام مقال"""
lemmer = qalsadi.lemmatizer.Lemmatizer()
# lemmatize a word
lemmer.lemmatize("يحتاج")

'احتاج'

In [ ]:
ds["train"] = ds["train"].map(lambda example: {"dialogue_processed_tokenized_lemmatized": " ".join([lemmer.lemmatize(token) for token in example["dialogue_processed_tokenized"]])})

Parameter 'function'=<function <lambda> at 0x7d756fa24a40> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
WARNING:datasets.fingerprint:Parameter 'function'=<function <lambda> at 0x7d756fa24a40> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.

Map:   0%|          | 0/24813 [00:00<?, ? examples/s]

In [ ]:
ds["train"]["dialogue_processed_tokenized_lemmatized"][50]

'جو : رسل رسالة بريد إلكترون حول ليفاندوفسكا . ميرف : ماذا حدث ؟ جو : ميرف : ووو ! جو : تم نقل إلى مستشفى أن أعان من حصب . ميرف : كان لدى ماذا ؟ جو : جبى على أي شخص لدى اتصال مع خلال يوم الماضيين تلقيح . ميرف : حسن حظ لم آر منذ فصل دراسة أخير ... جو : على ، هي معلم أطروحة :( ميرف : ماذا فعل ؟ جو : إن نظم لقاح في مبنى رئيس من 17 حتى تاسع عشر . ميرف : على أن ذهب ! جو : أعرف ... بدأ تو عمل ، ذا ليس لد كثير من وقت . ميرف : هيا ، هذا مهم حق . جو : حاول قويم ذلك قبل عمل في ثامن عشر ، وآمل ألا قد يوم أكمل ...'

In [ ]:
ds["train"] = ds["train"].map(lambda example: {"summary_processed_tokenized_lemmatized": " ".join([s_stemmer.stem(token) for token in example["summary_processed_tokenized"]])})

Map:   0%|          | 0/24813 [00:00<?, ? examples/s]

In [ ]:
ds["train"]["summary_processed_tokenized_lemmatized"][50]

'يفاندوفس لد حصب . هنا لقاح في مبنى رييس من 17 حتى تاسع عشر لكل من كان على اتصال معه .'

## Saving the Dataset to Google Drive after Preprocessing

In [ ]:
pip install datasets

Collecting datasets
  Downloading datasets-4.4.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.20.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (22.0.0)
Collecting dill<0.4.1,>=0.3.0 (from datasets)
  Downloading dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting multiprocess<0.70.19 (from datasets)
  Downloading multiprocess-0.70.18-py312-none-any.whl.metadata (7.5 kB)
Collecting fsspec<=2025.10.0,>=2023.1.0 (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading fsspec-2025.10.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.0)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading propcache-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading yarl-1.22.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.1/75.1 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-4.4.1-py3-none-any.whl (511 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.6/511.6 kB 22.9 MB/s eta 0:00:00
Downloading dill-0.4.0-py3-none-any.whl (119 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.7/119.7 kB 10.6 MB/s eta 0:00:00
Downloading fsspec-2025.10.0-py3-none-any.whl (200 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.0/201.0 kB 17.6 MB/s eta 0:00:00
Downloading multiprocess-0.70.18-py312-none-any.whl (150 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.3/150.3 kB 13.5 MB/s eta 0:00:00
Downloading xxhash-3.6.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.9/193.9 kB 18.2 MB/s eta 0:00:00
Downloading aiohttp-3.13.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 65.1 MB/s eta 0:00:00
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (242 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.4/242.4 kB 17.8 MB/s eta 0:00:00
Downloading propcache-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (221 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 221.6/221.6 kB 18.8 MB/s eta 0:00:00
Downloading yarl-1.22.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (377 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 377.3/377.3 kB 27.3 MB/s eta 0:00:00
Installing collected packages: xxhash, propcache, fsspec, frozenlist, dill, aiohappyeyeballs, yarl, multiprocess, aiosignal, aiohttp, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.12.0
    Uninstalling fsspec-2025.12.0:
      Successfully uninstalled fsspec-2025.12.0
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.2 aiosignal-1.4.0 datasets-4.4.1 dill-0.4.0 frozenlist-1.8.0 fsspec-2025.10.0 multiprocess-0.70.18 propcache-0.4.1 xxhash-3.6.0 yarl-1.22.0

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

ds.save_to_disk("/content/drive/MyDrive/my_saved_dataset")

ValueError: mount failed

## Loading the Dataset to Google Drive after Preprocessing

In [ ]:
from google.colab import drive
drive.mount("/content/drive")
from datasets import load_from_disk # Added this import statement
ds = load_from_disk("/content/drive/MyDrive/my_saved_dataset")

#Data Split

In [ ]:
ds = ds["train"]

In [ ]:
from datasets import DatasetDict

# train + temp
split1 = ds.train_test_split(test_size=0.2, seed=42)

# validation + test
split2 = split1["test"].train_test_split(test_size=0.5, seed=42)

ds = DatasetDict({
    "train": split1["train"],
    "validation": split2["train"],
    "test": split2["test"],
})

In [ ]:
for k in ds:
    print(k, len(ds[k]))

In [ ]:
ds

# Models

#ARAT5

##ARAT5-base-1024 No Processing

In [ ]:
from transformers import T5Tokenizer, AutoModelForSeq2SeqLM

tokenizer = T5Tokenizer.from_pretrained("UBC-NLP/AraT5v2-base-1024")
model = AutoModelForSeq2SeqLM.from_pretrained("UBC-NLP/AraT5v2-base-1024")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

In [ ]:
ar_prompt="عاصمة ألمانيا هي <extra_id_0> "
input_ids = tokenizer(ar_prompt, return_tensors="pt").input_ids
outputs = model.generate(input_ids)
print("Tokenized input:", tokenizer.tokenize(ar_prompt))
print("Decoded output:", tokenizer.decode(outputs[0], skip_special_tokens=True))

Tokenized input: ['▁عاصمة', '▁ألمانيا', '▁هي', '<extra_id_0>']
Decoded output: برلين

### Input normal and output normal

In [ ]:
max_input_length = 384
max_target_length = 96

def tokenize_fn(batch):
    inputs = ["لخص الحوار: " + d for d in batch["dialogue"]]

    model_inputs = tokenizer(
        inputs,
        truncation=True,
        max_length=max_input_length,
    )

    labels = tokenizer(
        batch["summary"],
        truncation=True,
        max_length=max_target_length,
    )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
from datasets import DatasetDict
tokenized_splits = {}

for split in ds:
    tokenized_splits[split] = ds[split].map(
        tokenize_fn,
        batched=True,
        batch_size=16,      # small batch to prevent OOM
        remove_columns=ds[split].column_names,
        keep_in_memory=False
    )

tokenized_ds = DatasetDict(tokenized_splits)

Map:   0%|          | 0/19850 [00:00<?, ? examples/s]

Map:   0%|          | 0/2481 [00:00<?, ? examples/s]

Map:   0%|          | 0/2482 [00:00<?, ? examples/s]

In [ ]:
del ds
import gc
gc.collect()

188

In [ ]:
tokenized_ds

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 19850
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 2481
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 2482
    })
})

In [ ]:
pip install rouge-score

Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge-score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (4.67.1)
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=0cc8607f2dfa2c173185c55c7f50e4b547df54617811324dab9ea5c7283013b8
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: rouge-score
Successfully installed rouge-score-0.1.2

In [ ]:
pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.8 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
import evaluate

rouge = evaluate.load("rouge")

In [ ]:
def compute_metrics(eval_preds):
    preds, labels = eval_preds

    # Decode predictions
    decoded_preds = tokenizer.batch_decode(
        preds, skip_special_tokens=True
    )

    # Replace -100 in labels (Trainer uses this internally)
    labels = [
        [(token if token != -100 else tokenizer.pad_token_id) for token in label]
        for label in labels
    ]

    decoded_labels = tokenizer.batch_decode(
        labels, skip_special_tokens=True
    )

    result = rouge.compute(
        predictions=decoded_preds,
        references=decoded_labels,
    )

    # Return ROUGE-1, ROUGE-2, ROUGE-L
    return {
        "rouge1": result["rouge1"],
        "rouge2": result["rouge2"],
        "rougeL": result["rougeL"],
    }

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
)

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/arat5_out",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    fp16=True,
    learning_rate=3e-5,
    num_train_epochs=2,
    save_total_limit=1,
    logging_steps=100,
)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"].select(range(600)),
    tokenizer=tokenizer,
    data_collator=data_collator,
)

/tmp/ipython-input-1093713740.py:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 1

wandb: You chose 'Create a W&B account'
wandb: Create an account here: https://wandb.ai/authorize?signup=true&ref=models
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: ameramer8ameramer8 (jhona) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

KeyboardInterrupt:

In [ ]:
import evaluate
rouge = evaluate.load("rouge")

In [ ]:
import torch

val_subset = tokenized_ds["validation"].select(range(40))  # 🔹 small subset
preds = []
refs = []

model.eval()
for i, batch in enumerate(val_subset):
    input_ids = torch.tensor(batch["input_ids"]).unsqueeze(0).to(model.device)
    attention_mask = torch.tensor(batch["attention_mask"]).unsqueeze(0).to(model.device)

    with torch.no_grad():
        output = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=96,
            num_beams=1,
        )

    preds.append(tokenizer.decode(output[0], skip_special_tokens=True))

    labels = [x if x != -100 else tokenizer.pad_token_id for x in batch["label"]]
    refs.append(tokenizer.decode(labels, skip_special_tokens=True))

    torch.cuda.empty_cache()  # 🔹 clear GPU memory each loop

In [ ]:
results = rouge.compute(predictions=preds, references=refs)
print(results)

{'rouge1': np.float64(0.362732683982684), 'rouge2': np.float64(0.20805555555555555), 'rougeL': np.float64(0.3633441558441558), 'rougeLsum': np.float64(0.3627489177489177)}

In [ ]:
trainer.evaluate(tokenized_ds["test"].select(range(40))) # Reduced for faster testing

##ARAT5-base-1024 Stemmed

In [ ]:
from transformers import T5Tokenizer, AutoModelForSeq2SeqLM

tokenizer = T5Tokenizer.from_pretrained("UBC-NLP/AraT5v2-base-1024")
model = AutoModelForSeq2SeqLM.from_pretrained("UBC-NLP/AraT5v2-base-1024")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

In [ ]:
ar_prompt="عاصمة ألمانيا هي <extra_id_0> "
input_ids = tokenizer(ar_prompt, return_tensors="pt").input_ids
outputs = model.generate(input_ids)
print("Tokenized input:", tokenizer.tokenize(ar_prompt))
print("Decoded output:", tokenizer.decode(outputs[0], skip_special_tokens=True))

Tokenized input: ['▁عاصمة', '▁ألمانيا', '▁هي', '<extra_id_0>']
Decoded output: برلين

#### Input Stemmed and output normal

In [ ]:
max_input_length = 384
max_target_length = 96

def tokenize_fn(batch):
    inputs = ["لخص الحوار: " + d for d in batch["dialogue_processed_tokenized_stemmed"]]

    model_inputs = tokenizer(
        inputs,
        truncation=True,
        max_length=max_input_length,
    )

    labels = tokenizer(
        batch["summary"],
        truncation=True,
        max_length=max_target_length,
    )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
from datasets import DatasetDict
tokenized_splits = {}

for split in ds:
    tokenized_splits[split] = ds[split].map(
        tokenize_fn,
        batched=True,
        batch_size=16,      # small batch to prevent OOM
        remove_columns=ds[split].column_names,
        keep_in_memory=False
    )

tokenized_ds = DatasetDict(tokenized_splits)

Map:   0%|          | 0/19850 [00:00<?, ? examples/s]

Map:   0%|          | 0/2481 [00:00<?, ? examples/s]

Map:   0%|          | 0/2482 [00:00<?, ? examples/s]

In [ ]:
tokenized_ds

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 19850
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 2481
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 2482
    })
})

In [ ]:
del ds
import gc
gc.collect()

237

In [ ]:
import evaluate

rouge = evaluate.load("rouge")

In [ ]:
def compute_metrics(eval_preds):
    preds, labels = eval_preds

    # Decode predictions
    decoded_preds = tokenizer.batch_decode(
        preds, skip_special_tokens=True
    )

    # Replace -100 in labels (Trainer uses this internally)
    labels = [
        [(token if token != -100 else tokenizer.pad_token_id) for token in label]
        for label in labels
    ]

    decoded_labels = tokenizer.batch_decode(
        labels, skip_special_tokens=True
    )

    result = rouge.compute(
        predictions=decoded_preds,
        references=decoded_labels,
    )

    # Return ROUGE-1, ROUGE-2, ROUGE-L
    return {
        "rouge1": result["rouge1"],
        "rouge2": result["rouge2"],
        "rougeL": result["rougeL"],
    }

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
)

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/arat5_out_stemmed",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    fp16=True,
    learning_rate=3e-5,
    num_train_epochs=2,
    save_total_limit=1,
    logging_steps=100,
)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"].select(range(600)),
    tokenizer=tokenizer,
    data_collator=data_collator,
)

/tmp/ipython-input-1557801459.py:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

TrainOutput(global_step=150, training_loss=5.431741841634115, metrics={'train_runtime': 252.8848, 'train_samples_per_second': 4.745, 'train_steps_per_second': 0.593, 'total_flos': 273111533217792.0, 'train_loss': 5.431741841634115, 'epoch': 2.0})

In [ ]:
import evaluate
rouge = evaluate.load("rouge")

In [ ]:
import torch

val_subset = tokenized_ds["validation"].select(range(40))  # 🔹 small subset
preds = []
refs = []

model.eval()
for i, batch in enumerate(val_subset):
    input_ids = torch.tensor(batch["input_ids"]).unsqueeze(0).to(model.device)
    attention_mask = torch.tensor(batch["attention_mask"]).unsqueeze(0).to(model.device)

    with torch.no_grad():
        output = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=96,
            num_beams=1,
        )

    preds.append(tokenizer.decode(output[0], skip_special_tokens=True))

    labels = [x if x != -100 else tokenizer.pad_token_id for x in batch["labels"]]
    refs.append(tokenizer.decode(labels, skip_special_tokens=True))

    torch.cuda.empty_cache()  # 🔹 clear GPU memory each loop

In [ ]:
results = rouge.compute(predictions=preds, references=refs)
print(results)

{'rouge1': np.float64(0.29833333333333334), 'rouge2': np.float64(0.1325), 'rougeL': np.float64(0.28333333333333327), 'rougeLsum': np.float64(0.2817857142857142)}

In [ ]:
trainer.evaluate(tokenized_ds["test"].select(range(40))) # Reduced for faster testing

{'eval_loss': 3.6590685844421387,
 'eval_runtime': 0.6567,
 'eval_samples_per_second': 60.907,
 'eval_steps_per_second': 7.613,
 'epoch': 2.0}

#MT5

##MT5-Small 0 rouge

In [ ]:
from transformers import MT5Tokenizer, MT5ForConditionalGeneration

model_name = "google/mt5-small"
tokenizer = MT5Tokenizer.from_pretrained(model_name)
model = MT5ForConditionalGeneration.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/82.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/553 [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'T5Tokenizer'.
The class this function is called from is 'MT5Tokenizer'.
You are using the default legacy behaviour of the <class 'transformers.models.mt5.tokenization_mt5.MT5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

pytorch_model.bin:   0%|          | 0.00/1.20G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.20G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

### Input processed and output normal

In [ ]:

max_input_length = 384
max_target_length = 96

def tokenize_fn(batch):
    inputs = ["لخص الحوار: " + d for d in batch["dialogue_processed"]]

    model_inputs = tokenizer(
        inputs,
        truncation=True,
        max_length=max_input_length,
    )

    labels = tokenizer(
        batch["summary"],
        truncation=True,
        max_length=max_target_length,
    )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
from datasets import DatasetDict
tokenized_splits = {}

for split in ds:
    tokenized_splits[split] = ds[split].map(
        tokenize_fn,
        batched=True,
        batch_size=16,      # small batch to prevent OOM
        remove_columns=ds[split].column_names,
        keep_in_memory=False
    )

tokenized_ds = DatasetDict(tokenized_splits)

Map:   0%|          | 0/19850 [00:00<?, ? examples/s]

Map:   0%|          | 0/2481 [00:00<?, ? examples/s]

Map:   0%|          | 0/2482 [00:00<?, ? examples/s]

In [ ]:
del ds
import gc
gc.collect()

185

In [ ]:
tokenized_ds

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 19850
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 2481
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 2482
    })
})

In [ ]:
pip install rouge-score

Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge-score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (4.67.1)
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=0798b895a6f70be855cff625f11292379d083af105378b24a353c3a36a2f6ed3
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: rouge-score
Successfully installed rouge-score-0.1.2

In [ ]:
pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.9 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
import evaluate

rouge = evaluate.load("rouge")

Downloading builder script: 0.00B [00:00, ?B/s]

In [ ]:
def compute_metrics(eval_preds):
    preds, labels = eval_preds

    # Decode predictions
    decoded_preds = tokenizer.batch_decode(
        preds, skip_special_tokens=True
    )

    # Replace -100 in labels (Trainer uses this internally)
    labels = [
        [(token if token != -100 else tokenizer.pad_token_id) for token in label]
        for label in labels
    ]

    decoded_labels = tokenizer.batch_decode(
        labels, skip_special_tokens=True
    )

    result = rouge.compute(
        predictions=decoded_preds,
        references=decoded_labels,
    )

    # Return ROUGE-1, ROUGE-2, ROUGE-L
    return {
        "rouge1": result["rouge1"],
        "rouge2": result["rouge2"],
        "rougeL": result["rougeL"],
    }

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
)

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/mt5_small_processed",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    fp16=True,
    learning_rate=3e-5,
    num_train_epochs=10,
    save_total_limit=1,
    logging_steps=100,
)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"].select(range(600)),
    tokenizer=tokenizer,
    data_collator=data_collator,
)

/tmp/ipython-input-1557801459.py:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

TrainOutput(global_step=750, training_loss=647543256059.9316, metrics={'train_runtime': 926.4161, 'train_samples_per_second': 6.477, 'train_steps_per_second': 0.81, 'total_flos': 1321099691520000.0, 'train_loss': 647543256059.9316, 'epoch': 10.0})

In [ ]:
pip install evaluate

Requirement already satisfied: evaluate in /usr/local/lib/python3.12/dist-packages (0.4.6)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)

In [ ]:


import evaluate
rouge = evaluate.load("rouge")

In [ ]:
import torch

val_subset = tokenized_ds["validation"].select(range(40))  # 🔹 small subset
preds = []
refs = []

model.eval()
for i, batch in enumerate(val_subset):
    input_ids = torch.tensor(batch["input_ids"]).unsqueeze(0).to(model.device)
    attention_mask = torch.tensor(batch["attention_mask"]).unsqueeze(0).to(model.device)

    with torch.no_grad():
        output = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=max_target_length,
            num_beams=1,
        )

    preds.append(tokenizer.decode(output[0], skip_special_tokens=True))

    labels = [x if x != -100 else tokenizer.pad_token_id for x in batch["labels"]]
    refs.append(tokenizer.decode(labels, skip_special_tokens=True))

    torch.cuda.empty_cache()  # 🔹 clear GPU memory each loop

In [ ]:
results = rouge.compute(predictions=preds, references=refs)
print(results)

{'rouge1': np.float64(0.0), 'rouge2': np.float64(0.0), 'rougeL': np.float64(0.0), 'rougeLsum': np.float64(0.0)}

In [ ]:
trainer.evaluate(tokenized_ds["test"].select(range(40))) # Reduced for faster testing

{'eval_loss': nan,
 'eval_runtime': 0.4065,
 'eval_samples_per_second': 98.393,
 'eval_steps_per_second': 12.299,
 'epoch': 10.0}

##MT5-Small

In [ ]:
from transformers import MT5Tokenizer, MT5ForConditionalGeneration

model_name = "google/mt5-small"
tokenizer = MT5Tokenizer.from_pretrained(model_name)
model = MT5ForConditionalGeneration.from_pretrained(model_name)

### Input processed and output normal

In [ ]:

max_input_length = 384
max_target_length = 128 # Increased target length

def tokenize_fn(batch):
    inputs = ["لخص الحوار: " + d for d in batch["dialogue"]] # Changed to use raw dialogue

    model_inputs = tokenizer(
        inputs,
        truncation=True,
        max_length=max_input_length,
    )

    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            batch["summary"], # Changed to use raw summary
            truncation=True,
            max_length=max_target_length,
        )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
from datasets import DatasetDict
tokenized_splits = {}

for split in ds:
    tokenized_splits[split] = ds[split].map(
        tokenize_fn,
        batched=True,
        batch_size=16,      # small batch to prevent OOM
        remove_columns=ds[split].column_names,
        keep_in_memory=False
    )

tokenized_ds = DatasetDict(tokenized_splits)

In [ ]:
del ds
import gc
gc.collect()

In [ ]:
tokenized_ds

In [ ]:
pip install rouge-score

In [ ]:
pip install evaluate

In [ ]:
import evaluate

rouge = evaluate.load("rouge")

In [ ]:
def compute_metrics(eval_preds):
    preds, labels = eval_preds

    # Decode predictions
    decoded_preds = tokenizer.batch_decode(
        preds, skip_special_tokens=True
    )

    # Replace -100 in labels (Trainer uses this internally)
    labels = [
        [(token if token != -100 else tokenizer.pad_token_id) for token in label]
        for label in labels
    ]

    decoded_labels = tokenizer.batch_decode(
        labels, skip_special_tokens=True
    )

    result = rouge.compute(
        predictions=decoded_preds,
        references=decoded_labels,
    )

    # Return ROUGE-1, ROUGE-2, ROUGE-L
    return {
        "rouge1": result["rouge1"],
        "rouge2": result["rouge2"],
        "rougeL": result["rougeL"],
    }

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
)

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/mt5_small_raw",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    fp16=True,
    learning_rate=3e-5,
    num_train_epochs=5,
    save_total_limit=1,
    logging_steps=100,
)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"].select(range(600)),
    tokenizer=tokenizer,
    data_collator=data_collator,
)

In [ ]:
trainer.train()

In [ ]:
pip install evaluate

In [ ]:


import evaluate
rouge = evaluate.load("rouge")

In [ ]:
import torch

val_subset = tokenized_ds["validation"].select(range(40))  # 🔹 small subset
preds = []
refs = []

model.eval()
for i, batch in enumerate(val_subset):
    input_ids = torch.tensor(batch["input_ids"]).unsqueeze(0).to(model.device)
    attention_mask = torch.tensor(batch["attention_mask"]).unsqueeze(0).to(model.device)

    with torch.no_grad():
        output = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=max_target_length,
            num_beams=1
        )

    preds.append(tokenizer.decode(output[0], skip_special_tokens=True))

    labels = [x if x != -100 else tokenizer.pad_token_id for x in batch["labels"]]
    refs.append(tokenizer.decode(labels, skip_special_tokens=True))

    torch.cuda.empty_cache()  # 🔹 clear GPU memory each loop

In [ ]:
results = rouge.compute(predictions=preds, references=refs)
print(results)

In [ ]:
trainer.evaluate(tokenized_ds["test"].select(range(40))) # Reduced for faster testing

#Tiny-Mbart

##Only Processed data not 600

In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("sshleifer/tiny-mbart")
model = AutoModelForSeq2SeqLM.from_pretrained("sshleifer/tiny-mbart")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.53M [00:00<?, ?B/s]

In [ ]:
# Arabic language codes
tokenizer.src_lang = "ar_AR"
tokenizer.tgt_lang = "ar_AR"

In [ ]:
max_input_length = 384
max_target_length = 128

def tokenize_fn(batch):
    model_inputs = tokenizer(
        batch["dialogue_processed"],          # RAW Arabic text
        truncation=True,
        max_length=max_input_length
    )

    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            batch["summary"],
            truncation=True,
            max_length=max_target_length
        )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
from datasets import DatasetDict

train_ds = ds["train"].select(range(2000))
val_ds   = ds["validation"].select(range(200))

tokenized_train = train_ds.map(
    tokenize_fn,
    batched=True,
    batch_size=16,
    remove_columns=train_ds.column_names
)

tokenized_val = val_ds.map(
    tokenize_fn,
    batched=True,
    batch_size=16,
    remove_columns=val_ds.column_names
)

tokenized_ds = DatasetDict({
    "train": tokenized_train,
    "validation": tokenized_val
})

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:4169: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model
)

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/tiny_mbart_out",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    fp16=True,
    learning_rate=3e-5,
    num_train_epochs=5,
    save_total_limit=1,
    logging_steps=50,
    report_to="none",

)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

/tmp/ipython-input-1497134320.py:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/transformers/modeling_utils.py:3918: UserWarning: Moving the following attributes in the config to the generation config: {'num_beams': 2}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(

TrainOutput(global_step=1250, training_loss=12.426584814453125, metrics={'train_runtime': 244.1522, 'train_samples_per_second': 40.958, 'train_steps_per_second': 5.12, 'total_flos': 2849532480.0, 'train_loss': 12.426584814453125, 'epoch': 5.0})

In [ ]:
pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.5 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
pip install rouge_score

Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.1)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=ae982fd2e1f29e33b737a70945fedc2fe96b138345e567f58024b07a7497a473
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2

In [ ]:
import evaluate, torch
rouge = evaluate.load("rouge")

val_subset = tokenized_ds["validation"].select(range(100))

preds = []
refs = []

model.eval()
for batch in val_subset:
    input_ids = torch.tensor(batch["input_ids"]).unsqueeze(0).to(model.device)
    attention_mask = torch.tensor(batch["attention_mask"]).unsqueeze(0).to(model.device)

    with torch.no_grad():
        output = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=128,
            num_beams=3,
            forced_bos_token_id=tokenizer.lang_code_to_id["ar_AR"]
        )

    pred = tokenizer.decode(output[0], skip_special_tokens=True)

    labels = [x if x != -100 else tokenizer.pad_token_id for x in batch["labels"]]
    ref = tokenizer.decode(labels, skip_special_tokens=True)

    preds.append(pred)
    refs.append(ref)

results = rouge.compute(predictions=preds, references=refs)
print(results)

{'rouge1': np.float64(0.0), 'rouge2': np.float64(0.0), 'rougeL': np.float64(0.0), 'rougeLsum': np.float64(0.0)}

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    eval_dataset=tokenized_ds["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

trainer.train()

/tmp/ipython-input-2065951418.py:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

KeyboardInterrupt:

##Only Processed data 600

In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("sshleifer/tiny-mbart")
model = AutoModelForSeq2SeqLM.from_pretrained("sshleifer/tiny-mbart")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.53M [00:00<?, ?B/s]

In [ ]:
# Arabic language codes
tokenizer.src_lang = "ar_AR"
tokenizer.tgt_lang = "ar_AR"

In [ ]:
max_input_length = 384
max_target_length = 128

def tokenize_fn(batch):
    model_inputs = tokenizer(
        batch["dialogue"],          # RAW Arabic text
        truncation=True,
        max_length=max_input_length
    )

    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            batch["summary"],
            truncation=True,
            max_length=max_target_length
        )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
from datasets import DatasetDict
tokenized_splits = {}

for split in ds:
    tokenized_splits[split] = ds[split].map(
        tokenize_fn,
        batched=True,
        batch_size=16,      # small batch to prevent OOM
        remove_columns=ds[split].column_names,
        keep_in_memory=False
    )

tokenized_ds = DatasetDict(tokenized_splits)

tokenized_ds

Map:   0%|          | 0/19850 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:4169: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(

Map:   0%|          | 0/2481 [00:00<?, ? examples/s]

Map:   0%|          | 0/2482 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 19850
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 2481
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 2482
    })
})

In [ ]:
del ds
import gc
gc.collect()

188

In [ ]:
pip install rouge_score

Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.1)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=905633d58e803e5b93649bbf5cf9948a01fdc9d93f55bc3a4fe202d5c61bcd25
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2

In [ ]:
import evaluate

rouge = evaluate.load("rouge")


def compute_metrics(eval_preds):
    preds, labels = eval_preds

    # Decode predictions
    decoded_preds = tokenizer.batch_decode(
        preds, skip_special_tokens=True
    )

    # Replace -100 in labels (Trainer uses this internally)
    labels = [
        [(token if token != -100 else tokenizer.pad_token_id) for token in label]
        for label in labels
    ]

    decoded_labels = tokenizer.batch_decode(
        labels, skip_special_tokens=True
    )

    result = rouge.compute(
        predictions=decoded_preds,
        references=decoded_labels,
    )

    # Return ROUGE-1, ROUGE-2, ROUGE-L
    return {
        "rouge1": result["rouge1"],
        "rouge2": result["rouge2"],
        "rougeL": result["rougeL"],
    }

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
)

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/tinymbart_out",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    fp16=True,
    learning_rate=3e-5,
    num_train_epochs=2,
    save_total_limit=1,
    logging_steps=100,
)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"].select(range(600)),
    tokenizer=tokenizer,
    data_collator=data_collator,
)

/tmp/ipython-input-1557801459.py:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

Error: You must call wandb.init() before wandb.log()

In [ ]:
pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.5 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
pip install rouge_score

Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.1)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=ae982fd2e1f29e33b737a70945fedc2fe96b138345e567f58024b07a7497a473
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2

In [ ]:
import evaluate
rouge = evaluate.load("rouge")

{'rouge1': np.float64(0.0), 'rouge2': np.float64(0.0), 'rougeL': np.float64(0.0), 'rougeLsum': np.float64(0.0)}

In [ ]:
import torch

val_subset = tokenized_ds["validation"].select(range(40))  # 🔹 small subset
preds = []
refs = []

model.eval()
for i, batch in enumerate(val_subset):
    input_ids = torch.tensor(batch["input_ids"]).unsqueeze(0).to(model.device)
    attention_mask = torch.tensor(batch["attention_mask"]).unsqueeze(0).to(model.device)

    with torch.no_grad():
        output = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=96,
            num_beams=1,
        )

    preds.append(tokenizer.decode(output[0], skip_special_tokens=True))

    labels = [x if x != -100 else tokenizer.pad_token_id for x in batch["labels"]]
    refs.append(tokenizer.decode(labels, skip_special_tokens=True))

    torch.cuda.empty_cache()  # 🔹 clear GPU memory each loop


results = rouge.compute(predictions=preds, references=refs)
print(results)

/tmp/ipython-input-2065951418.py:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

KeyboardInterrupt:

In [ ]:
trainer.evaluate(tokenized_ds["test"].select(range(40))) # Reduced for faster testing

##Raw Data

In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("sshleifer/tiny-mbart")
model = AutoModelForSeq2SeqLM.from_pretrained("sshleifer/tiny-mbart")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.53M [00:00<?, ?B/s]

In [ ]:
# Arabic language codes
tokenizer.src_lang = "ar_AR"
tokenizer.tgt_lang = "ar_AR"

In [ ]:
max_input_length = 384
max_target_length = 128

def tokenize_fn(batch):
    model_inputs = tokenizer(
        batch["dialogue"],          # RAW Arabic text
        truncation=True,
        max_length=max_input_length
    )

    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            batch["summary"],
            truncation=True,
            max_length=max_target_length
        )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
from datasets import DatasetDict

train_ds = ds["train"].select(range(2000))
val_ds   = ds["validation"].select(range(200))

tokenized_train = train_ds.map(
    tokenize_fn,
    batched=True,
    batch_size=16,
    remove_columns=train_ds.column_names
)

tokenized_val = val_ds.map(
    tokenize_fn,
    batched=True,
    batch_size=16,
    remove_columns=val_ds.column_names
)

tokenized_ds = DatasetDict({
    "train": tokenized_train,
    "validation": tokenized_val
})

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:4169: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(

model.safetensors:   0%|          | 0.00/1.52M [00:00<?, ?B/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model
)

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/tiny_mbart_out_raw",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    fp16=True,
    learning_rate=3e-5,
    num_train_epochs=5,
    save_total_limit=1,
    logging_steps=50,
    report_to="none",

)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

/tmp/ipython-input-1497134320.py:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/transformers/modeling_utils.py:3918: UserWarning: Moving the following attributes in the config to the generation config: {'num_beams': 2}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(

TrainOutput(global_step=1250, training_loss=12.42633369140625, metrics={'train_runtime': 227.868, 'train_samples_per_second': 43.885, 'train_steps_per_second': 5.486, 'total_flos': 2881681920.0, 'train_loss': 12.42633369140625, 'epoch': 5.0})

In [ ]:
pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 8.3 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
pip install rouge_score

Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.1)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=03c61b60695874925f4bb947cf5d5841cc65a639cbba2f003922082621c54dda
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2

In [ ]:
import evaluate, torch
rouge = evaluate.load("rouge")

val_subset = tokenized_ds["validation"].select(range(100))

preds = []
refs = []

model.eval()
for batch in val_subset:
    input_ids = torch.tensor(batch["input_ids"]).unsqueeze(0).to(model.device)
    attention_mask = torch.tensor(batch["attention_mask"]).unsqueeze(0).to(model.device)

    with torch.no_grad():
        output = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=128,
            num_beams=3,
            forced_bos_token_id=tokenizer.lang_code_to_id["ar_AR"]
        )

    pred = tokenizer.decode(output[0], skip_special_tokens=True)

    labels = [x if x != -100 else tokenizer.pad_token_id for x in batch["labels"]]
    ref = tokenizer.decode(labels, skip_special_tokens=True)

    preds.append(pred)
    refs.append(ref)

results = rouge.compute(predictions=preds, references=refs)
print(results)

Downloading builder script: 0.00B [00:00, ?B/s]

{'rouge1': np.float64(0.0), 'rouge2': np.float64(0.0), 'rougeL': np.float64(0.0), 'rougeLsum': np.float64(0.0)}